### ISSUE TITLE
fluxcalib crash: null ivar

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1156]
Using desispec/0.39.1:
```
desi_compute_fluxcalibration --delta-color-cut 0.1 \
  --infile /global/cfs/cdirs/desi/spectro/redux/cascades/exposures/20210106/00071101/frame-r1-00071101.fits \
  --sky /global/cfs/cdirs/desi/spectro/redux/cascades/exposures/20210106/00071101/sky-r1-00071101.fits \
  --fiberflat /global/cfs/cdirs/desi/spectro/redux/cascades/calibnight/20210106/fiberflatnight-r1-20210106.fits \
  --models /global/cfs/cdirs/desi/spectro/redux/cascades/exposures/20210106/00071101/stdstars-1-00071101.fits \
  --outfile $SCRATCH/fluxcalib-r1-00071101.fits 
...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.39.1/bin/desi_compute_fluxcalibration", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.39.1', 'desi_compute_fluxcalibration')
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.39.1/lib/python3.8/site-packages/desispec-0.39.1-py3.8.egg/EGG-INFO/scripts/desi_compute_fluxcalibration", line 16, in <module>
    fluxcal.main(args)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.39.1/lib/python3.8/site-packages/desispec-0.39.1-py3.8.egg/desispec/scripts/fluxcalibration.py", line 196, in main
    fluxcalib = compute_flux_calibration(frame, model_wave, model_flux, model_fibers%500, highest_throughput_nstars = args.highest_throughput)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.39.1/lib/python3.8/site-packages/desispec-0.39.1-py3.8.egg/desispec/fluxcalibration.py", line 1104, in compute_flux_calibration
    raise ValueError("null ivar, cannot calibrate this frame")
ValueError: null ivar, cannot calibrate this frame
```
It might not be fluxcalib's fault, but it could exit (still with an error) more gracefully.  Trace back if the null ivar is unavoidable or evidence of some other problem.

**Comment by julienguy** [comment]
solved in PR #1157
