### ISSUE TITLE
missing TSNR column -> coadd failure

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1227]
```
cd /global/cfs/cdirs/desi/spectro/redux/denali
desi_coadd_spectra --nproc 16 -i tiles/pernight/80613/20210324/spectra-0-80613-20210324.fits -o $SCRATCH/coadd-0-80613-20210324.fits
...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/bin/desi_coadd_spectra", line 16, in <module>
    coadd_spectra.main(args)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/lib/python3.8/site-packages/desispec/scripts/coadd_spectra.py", line 139, in main
    coadd(spectra,cosmics_nsig=args.nsig)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/lib/python3.8/site-packages/desispec/coaddition.py", line 252, in coadd
    compute_coadd_scores(spectra, orig_scores, update_coadd=True)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/lib/python3.8/site-packages/desispec/specscore.py", line 107, in compute_coadd_scores
    scores[col] += scores[colbrz]
KeyError: 'TSNR2_ELG_Z'
```

**Comment by akremin** [comment]
This was also seen when doing "perexp" redshifts for Denali. It occurred for 6 petals. Each petal had a bad z camera that was flagged. Since the perexp are single exposure, that meant no z data was passed to the script that creates spectra, which likely led to the lack of z camera TSNR2 values. The coadd assumes that they exist for all cameras, which led to the error. 

We either:
1) Fill scores TSNR2 values to 0's for all cameras that don't exist in the inputs.
2) Setup the coadd script to not expect all cameras.

Example log file:
/global/cfs/cdirs/desi/spectro/redux/denali/tiles/perexp/81064/00082505/coadd-2-81064-exp00082505.log

Snippet:
```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/bin/desi_coadd_spectra", line 16, in <module>
    coadd_spectra.main(args)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/lib/python3.8/site-packages/desispec/scripts/coadd_spectra.py", line 139, in main
    coadd(spectra,cosmics_nsig=args.nsig)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/lib/python3.8/site-packages/desispec/coaddition.py", line 252, in coadd
    compute_coadd_scores(spectra, orig_scores, update_coadd=True)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.40.1/lib/python3.8/site-packages/desispec/specscore.py", line 107, in compute_coadd_scores
    scores[col] += scores[colbrz]
KeyError: 'TSNR2_ELG_Z'
```

**Comment by sbailey** [comment]
I think TSNR2=0 for missing cameras is the algorithmically correct thing to do.
