### ISSUE TITLE
TSNR2 afterburner crashes when all exposures on a night are flagged as bad

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1336]
When running the afterburner for 20210710 (a night with 3 science exposures, all of which were flagged as bad data quality) the afterburner crashes with:

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 1010, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 886, in main
    tsnr2_expid_table = vstack(tsnr2_expid)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/operations.py", line 376, in vstack
    tables = _get_list_of_tables(tables)  # validates input
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/operations.py", line 50, in _get_list_of_tables
    raise ValueError('no values provided to stack.')
ValueError: no values provided to stack.
```

Command run:
`desi_tsnr_afterburner -o ${DESI_SPECTRO_REDUX}/${SPECPROD}/tsnr-exposures.fits --prod ${SPECPROD} --tile-completeness ${DESI_SPECTRO_REDUX}/${SPECPROD}/tiles.csv  --gfa-proc-dir /global/cfs/cdirs/desi/survey/GFA/ --compute-skymags --update --nproc 8 --nights 20210710`

**Comment by akremin** [comment]
This was superseded by #1345
