### ISSUE TITLE
desi_tsnr_afterburner crashes if no cframes in a night

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1345]
desi_tsnr_afterburner crashes if no cframes in a night. This wouldn't matter if the night had no science exposures, but some nights such as 20210710 had science exposures that were deemed poor quality and weren't processed to flux calibrated spectra or redshifts. To be consistent in behavior, these exposures should be included as rows in the output table with EFFTIME_SPEC=0 (like all other exposures that didn't get cframes). 

#### Command 
```
desi_tsnr_afterburner -o /global/cfs/cdirs/desi/spectro/redux/kremin/tsnr-everest.fits --prod everest
--tile-completeness /global/cfs/cdirs/desi/spectro/redux/kremin/tiles-everest.csv
--aux /global/cfs/cdirs/desi/survey/observations/SV1/sv1-tiles.fits
--gfa-proc-dir /global/cfs/cdirs/desi/survey/GFA/
--compute-skymags --update --nproc 32 --nights 20210710
```

#### Output
```
INFO:desi_tsnr_afterburner:764:main: outfile = /global/cfs/cdirs/desi/spectro/redux/everest/exposures-everest.fits
INFO:desi_tsnr_afterburner:767:main: prod = /global/cfs/cdirs/desi/spectro/redux/everest
INFO:desi_tsnr_afterburner:826:main: cameras = ['b0', 'b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8', 'b9', 'r0', 'r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'z0', 'z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7', 'z8', 'z9']
INFO:desi_tsnr_afterburner:827:main: nights = [20210710]
INFO:desi_tsnr_afterburner:835:main: Eff. time scale factors = {'TSNR2_ELG_TO_EFFTIME_DARK': 8.6, 'TSNR2_LYA_TO_EFFTIME_DARK': 9.08, 'TSNR2_BGS_TO_EFFTIME_BRIGHT': 0.14}
INFO:desi_tsnr_afterburner:840:main: Will append pre-existing table /global/cfs/cdirs/desi/spectro/redux/everest/exposures-everest.fits
INFO:desi_tsnr_afterburner:863:one_night: 20210710 [98135, 98136, 98137, 98138, 98139, 98151, 98152, 98153, 98156, 98157, 98158, 98161, 98162, 98163, 98166, 98167, 98168, 98271, 98272, 98273]
INFO:desi_tsnr_afterburner:878:one_night: Multiprocessing with 32 procs
WARNING: leap-second auto-update failed due to the following exception: RuntimeError('Cache is locked after 5.02 s. This may indicate an astropy bug or that kill -9 was used. If you want to unlock the cache remove the directory /global/homes/d/desi/.astropy/cache/download/py3/lock.') [astropy.time.core]
INFO:desi_tsnr_afterburner:934:main: Gathering TSNR tmp tables (over ranks: False, 1)
WARNING:desi_tsnr_afterburner:949:main: /global/cfs/cdirs/desi/spectro/redux/everest/exposures-everest_tmp.fits not found.
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 1090, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 962, in main
    tsnr2_expid_table = vstack(tsnr2_expid)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/operations.py", line 376, in vstack
    tables = _get_list_of_tables(tables)  # validates input
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/operations.py", line 50, in _get_list_of_tables
    raise ValueError('no values provided to stack.')
ValueError: no values provided to stack.
```

**Comment by akremin** [comment]
This was an issue again for the night of `20210922` in `daily`.

**Comment by akremin** [comment]
All nights listed or associated with this issue are now resolved.
