### ISSUE TITLE
desi_coadd_spectra does not work with cframes inputs

### ISSUE THREAD

**Issue by rongpu** [desihub/desispec#1359]
`desi_coadd_spectra` no longer works with cframes inputs.

Example:
```
source /global/cfs/cdirs/desi/software/desi_environment.sh 21.7d
export INDIR=/global/cfs/cdirs/desi/spectro/redux/everest/exposures
desi_coadd_spectra -i $INDIR/20210324/00081833/cframe-[brz]0-*.fits $INDIR/20210324/00081834/cframe-[brz]0-*.fits -o $CSCRATCH/80613/2/coadd-0-80613-subset2.fits
```

Error message:
```
...
INFO:coadd_spectra.py:151:main: coadding ...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.45.1/bin/desi_coadd_spectra", line 16, in <module>
    coadd_spectra.main(args)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.45.1/lib/python3.8/site-packages/desispec/scripts/coadd_spectra.py", line 152, in main
    coadd(spectra, cosmics_nsig=args.nsig, onetile=args.onetile)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.45.1/lib/python3.8/site-packages/desispec/coaddition.py", line 449, in coadd
    spectra.fibermap, exp_fibermap = coadd_fibermap(spectra.fibermap, onetile=onetile)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/0.45.1/lib/python3.8/site-packages/desispec/coaddition.py", line 243, in coadd_fibermap
    tfmap['COADD_NUMNIGHT'][i] = len(np.unique(fibermap['NIGHT'][jj]))
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 1602, in __getitem__
    return self.columns[item]
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 239, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'NIGHT'
```

**Comment by moustakas** [comment]
Fixed in #1616.
