### ISSUE TITLE
desi_tsnr_afterburner crashes in daily for 20210515 and 20210519

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1395]
`desi_tsnr_afterburner` still crashes in the `daily` specprod due to inconsistent tsnr datamodels on two specific nights. 

Backstory: Several cframes were reprocessed in daily after changes were made in the pipeline to include additional TSNR columns [`TSNR2_GPBDARK`, `TSNR2_GPBBRIGHT`, `TSNR2_GPBBACKUP`'] in the cframes. When old cframes and new cframes are present in the same night the afterburner crashes. This occurs for two nights in daily: 20210515 and 20210519.

#### Failing commands:
```
desi_tsnr_afterburner -o ./tsnr-exposures.fits --prod daily --tile-completeness ./tiles.csv --aux /global/cfs/cdirs/desi/survey/observations/SV1/sv1-tiles.fits --gfa-proc-dir /global/cfs/cdirs/desi/survey/GFA/ --compute-skymags --update --nproc 8 --nights 20210515
```

```
desi_tsnr_afterburner -o ./tsnr-exposures.fits --prod daily --tile-completeness ./tiles.csv --aux /global/cfs/cdirs/desi/survey/observations/SV1/sv1-tiles.fits --gfa-proc-dir /global/cfs/cdirs/desi/survey/GFA/ --compute-skymags --update --nproc 8 --nights 20210519
```

#### Relevant error message:
```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 1104, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 945, in main
    one_night(count, night, summary_rows, tmpfilename)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 903, in one_night
    tsnr2_expid_table,tsnr2_frame_table = compute_summary_tables(rows,efftime_config,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tsnr_afterburner", line 306, in compute_summary_tables
    masked_cam_summary = Table(rows=summary_rows, names=colnames)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 607, in __init__
    self._check_names_dtype(names, dtype, n_cols)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/table.py", line 829, in _check_names_dtype
    raise ValueError(
ValueError: Arguments "names" and "dtype" must match number of columns
```

**Comment by akremin** [comment]
Fixed with PR #1396
