### ISSUE TITLE
desi_tsnr_afterburner crashes when running on daily tables

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1401]
The names of the HDUs were changed to be more representative of the content of the files (a good thing), but the code now crashes for the old format in daily. 

Relevant output:
```
INFO:desi_tsnr_afterburner:872:main: Will append pre-existing table ./tsnr-exposures.fits
Traceback (most recent call last):
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/bin/desi_tsnr_afterburner", line 1122, in <module>
    main()
  File "/global/homes/k/kremin/workspace/testdesispec/desispec/bin/desi_tsnr_afterburner", line 873, in main
    preexisting_tsnr2_expid_table = Table.read(args.outfile,"EXPOSURES")
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/table/connect.py", line 52, in __call__
    out = registry.read(cls, *args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/registry.py", line 523, in read
    data = reader(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/fits/connect.py", line 215, in read_table_fits
    return read_table_fits(hdulist, hdu=hdu,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/fits/connect.py", line 176, in read_table_fits
    hdu = input.index_of(hdu)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 750, in index_of
    raise KeyError(f'Extension {key!r} not found.')
KeyError: "Extension 'EXPOSURES' not found."
```

**Comment by akremin** [comment]
The daily tables are now updated to the new format and all new exposures and tiles summary files will be in the new format, so I will close this as no longer an issue.
