### ISSUE TITLE
desi_compute_fluxcalibration.py crash

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#141]
Using the data in the attached [fluxcalibcrash.tar.gz](https://github.com/desihub/desispec/files/181686/fluxcalibcrash.tar.gz) file [4.7M], the following desi_compute_fluxcalibration.py command crashes.  These data are also (temporarily) available on edison.nersc.gov in /scratch1/scratchdirs/sjbailey/desi/debug/fluxcalib.  It is possible that the underlying problem is with some upstream step creating a problematic input file.  If so, file a new ticket for that problem, but even then desi_flux_calibration.py should fail gracefully with a meaningful error message instead of a linear algebra error.

fiberflat is the upstream piece that has most recently changed algorithmically, so checking that input could be a good place to start.  This crash has appeared in 2 of the 4 integration cronjobs run this weekend, and also in the dc3a processing for the automated pipeline data challenge.
```
desi_compute_fluxcalibration.py \
    --infile frame-b0-00000002.fits \
    --fiberflat fiberflat-b0-00000000.fits \
    --fibermap fibermap-b0-00000000.fits \
    --models stdstars-sp0-00000002.fits \
    --sky sky-b0-00000002.fits \
    --outfile fluxcalib-b0-00000002.fits
WARNING:desi_compute_fluxcalibration.py:57:main: --fibermap is deprecated (and not used at all)
INFO:desi_compute_fluxcalibration.py:59:main: read frame
INFO:desi_compute_fluxcalibration.py:63:main: apply fiberflat
INFO:fiberflat.py:390:apply_fiberflat: starting
INFO:fiberflat.py:419:apply_fiberflat: done
INFO:desi_compute_fluxcalibration.py:70:main: subtract sky
INFO:sky.py:204:subtract_sky: starting
INFO:sky.py:216:subtract_sky: done
INFO:desi_compute_fluxcalibration.py:77:main: compute flux calibration
INFO:fluxcalibration.py:207:compute_flux_calibration: starting
INFO:fluxcalibration.py:260:compute_flux_calibration: iter 0 fiber 0
INFO:fluxcalibration.py:272:compute_flux_calibration: iter 0 solving
Traceback (most recent call last):
  File "/global/homes/s/sjbailey/desi/git/desispec/bin/desi_compute_fluxcalibration.py", line 115, in <module>
    main()
  File "/global/homes/s/sjbailey/desi/git/desispec/bin/desi_compute_fluxcalibration.py", line 90, in main
    fluxcalib, indiv_stars = compute_flux_calibration(frame, model_wave, model_flux)
  File "/global/homes/s/sjbailey/desi/git/desispec/py/desispec/fluxcalibration.py", line 273, in compute_flux_calibration
    calibration=cholesky_solve(A.todense(),B)
  File "/global/homes/s/sjbailey/desi/git/desispec/py/desispec/linalg.py", line 27, in cholesky_solve
    UorL,lower = scipy.linalg.cho_factor(A, lower=lower, overwrite_a=overwrite)
  File "/global/common/edison/contrib/desi/edison/hpcports_gnu-8.2/scipy-0.17.0_7039ef88-8.2/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 132, in cho_factor
    check_finite=check_finite)
  File "/global/common/edison/contrib/desi/edison/hpcports_gnu-8.2/scipy-0.17.0_7039ef88-8.2/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 30, in _cholesky
    raise LinAlgError("%d-th leading minor not positive definite" % info)
numpy.linalg.linalg.LinAlgError: 2271-th leading minor not positive definite
```

**Comment by sbailey** [comment]
Further info:
* the condition number of the matrix is terrible: 2.5e18
* np.linalg.solve works but np.linalg.cholesky doesn't
* the input only has one standard star, and it has ivar=0 elements
* this problem occurs more commonly when there are fewer standard stars (this test case only has one)

For consideration:
* identify where ivar=0 for *all* input standard stars
* add a prior for just those wavelengths to keep the solution well behaved
* set calibivar[bad]=0, and also propagate into the output mask

**Comment by sbailey** [comment]
More info: for this particular test case with a single standard star, the basic problem is that it is trying to solve for an N-element calibration vector using an N-element input of which 2 elements are masked.  More variables than inputs.  Crash.

I'd be surprised if that is exactly what is going on for the dc3a crashes though, where there should be 10 standard stars per spectrograph, while solving for just one mean calibration vector.

Another approach would be to directly solve for the smoothed calibration vector instead of solving for the noisy calibration vector and then smoothing.
