### ISSUE TITLE
bad PSF fit/merging on bad r8A 20211026/00106162

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1471]
Extractions of multiple flats on 20211026 failed:
```
srun -n 20 -c 2 desi_extract_spectra -w 5760.0,7620.0,0.8 -i /global/cfs/cdirs/desi/spectro/redux/daily/preproc/20211026/00106177/preproc-r8-00106177.fits -p /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20211026/00106177/psf-r8-00106177.fits -o testframe.fits --psferr 0.1 --mpi
...
ERROR:extract.py:684:main_mpi: extract:  FAILED bundle 0, spectrum range 0:25
ERROR:extract.py:687:main_mpi: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/scripts/extract.py", line 674, in main_mpi
    mark_extraction = _extract_and_save(img, psf, bspecmin[b], bnspec[b], specmin,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/scripts/extract.py", line 744, in _extract_and_save
    results = ex2d(img.pix, img.ivar*(img.mask==0), psf, bspecmin,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/specter/master/py/specter/extract/ex2d.py", line 190, in ex2d
    ex2d_patch(subimg, subivar, psf,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/specter/master/py/specter/extract/ex2d.py", line 346, in ex2d_patch
    A = psf.projection_matrix(specrange, wavelengths, xyrange, use_cache=use_cache)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/specter/master/py/specter/psf/psf.py", line 667, in projection_matrix
    A = np.zeros( (nspec*nflux, ny*nx) )
ValueError: negative dimensions are not allowed
```

Negative dimensions are of course bad, but I haven't traced back to whether the input PSF is bad, or whether something about the preproc masking is confusing extractions.

Additionally it looks like the failed extractions aren't handled cleanly by desi_proc resulting in the jobs timing out rather than exiting with errors.

**Comment by sbailey** [comment]
Update:

arc exposure 20211026/00106162 r8A was particularly unhappy (OSTEPA=19.2 ADU):
![image](https://user-images.githubusercontent.com/218471/139928963-cc1642cf-ede4-4efd-a93f-fdfe409165ce.png)

the entire amp A gets flagged as bad, which led to a bad PSF fit for that individual exposure, e.g. the xy traces:
![image](https://user-images.githubusercontent.com/218471/139929043-66f65d34-3603-4605-8126-9ad48df2b27f.png)
(I'm guessing they are fit to the upper amp and then wildly extrapolating to the lower amp).

That was then merged into a bad nightly psf, which was so wrong in its wavelength solutions that it crashed extractions (they could have been more robust, but this was pathologically bad).

In the original processing, that amp wasn't masked as bad, the PSF fit proceeded with reasonable traces and was merged into an OK psfnight.

**Comment by sbailey** [comment]
Action items from discussion with Julien:
* if any amp triggers the bad readnoise rejection, don't fit the PSF at all for that exposure
  * but make sure that desi_proc et al exit in a way that doesn't cause the pipeline to stop
* let PSF merging proceed with the remaining exposures that did succeed
  * Note: we take 5 arc exposures specifically so that we can be robust to failures of individual exposures, not because we require 5 every time.  However, if r8 is unhappy for all of the arcs we will lose the PSF night.
* In principle we could still fit the PSF for the unaffected fibers, but that would require a deeper refactor to pass forward a PSF fiber mask and know how to use that when merging.
  * I think we'd need to do this if we permanently lost an amp, because then we'd be rejecting all the arc exposures for that camera and not getting a psfnight, even though we'd still like to make a psfnight for the remaining fibers so that we can use it for the science exposures where we don't care if we have 250 fibers with a junk PSF because we wouldn't be using those fibers on the science exposures anyway.
