### ISSUE TITLE
Singular Matrix Crash in Sky Subtraction 

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1485]
When doing the reprocessing of Sept and early October 2021 data there was only one unexplainable failure. This occurred for the exposure: 102501 on night 20210930. 

The crash comes in sky subtraction where a “singular matrix” error is raised.

Command:
`desi_compute_sky -i /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20210930/00102501/frame-r4-00102501.fits --fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20210930/fiberflatnight-r4-20210930.fits --o /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20210930/00102501/sky-r4-00102501.fits --adjust-wavelength --adjust-lsf --pca-corr /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/spec/sm1/skycorr-pca-sm1-r4.fits`

Output:
```
INFO:sky.py:71:main: starting
INFO:fibermap.py:337:read_fibermap: iotime 0.158 sec to read frame-r4-00102501.fits at 2021-11-16T19:17:32.273940
INFO:frame.py:216:read_frame: iotime 0.422 sec to read frame-r4-00102501.fits at 2021-11-16T19:17:32.326889
INFO:fiberflat.py:116:read_fiberflat: iotime 0.152 sec to read fiberflatnight-r4-20210930.fits at 2021-11-16T19:17:32.496118
INFO:fiberflat.py:724:apply_fiberflat: starting
INFO:fiberflat.py:746:apply_fiberflat: Also apply heliocentric correction scale factor 1.000043929586247 to fiber flat
INFO:fiberflat.py:768:apply_fiberflat: done
INFO:skycorr.py:147:read_skycorr_pca: iotime 0.172 sec to read skycorr-pca-sm1-r4.fits at 2021-11-16T19:17:32.827911
INFO:sky.py:184:compute_uniform_sky: starting
WARNING:sky.py:205:compute_uniform_sky: 56 sky fibers discarded (because ivar=0 or bad FIBERSTATUS), only 0 left.
INFO:sky.py:284:compute_uniform_sky: iter 0 solving
INFO:sky.py:292:compute_uniform_sky: cholesky failed, trying svd in iteration 0
/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/sky.py:293: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  deconvolved_sky[w]=np.linalg.lstsq(A_pos_def,B[w])[0]
INFO:sky.py:295:compute_uniform_sky: iter 0 compute chi2
INFO:sky.py:307:compute_uniform_sky: rejecting
INFO:sky.py:353:compute_uniform_sky: iter #0 chi2=0.000000 ndf=-2326 chi2pdf=0.000000 nout=0
INFO:sky.py:358:compute_uniform_sky: nout tot=0
INFO:sky.py:367:compute_uniform_sky: compute the parameter covariance
WARNING:sky.py:376:compute_uniform_sky: cholesky_solve_and_invert failed, switching to np.linalg.lstsq and np.linalg.pinv
INFO:sky.py:379:compute_uniform_sky: compute mean resolution
INFO:sky.py:385:compute_uniform_sky: compute convolved sky and ivar
INFO:sky.py:407:compute_uniform_sky: adjust the wavelength of sky spectrum on sky lines to improve sky subtraction ...
INFO:sky.py:439:compute_uniform_sky: Number of peaks: 0
INFO:sky.py:441:compute_uniform_sky: Wavelength of peaks: []
INFO:sky.py:601:compute_uniform_sky: Use PCA skycorr
INFO:sky.py:581:fit_and_interpolate: Will fit a linear combination on 4 components for wavelength
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_compute_sky", line 16, in <module>
    sky.main(args)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/scripts/sky.py", line 93, in main
    skymodel = compute_sky(frame,add_variance=(not args.no_extra_variance),\
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/sky.py", line 57, in compute_sky
    skymodel = compute_uniform_sky(frame, nsig_clipping=nsig_clipping,max_iterations=max_iterations,\
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/sky.py", line 604, in compute_uniform_sky
    correction = fit_and_interpolate(interpolated_sky_dwave,skyfibers,\
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/sky.py", line 590, in fit_and_interpolate
    AAi=np.linalg.inv(AA)
  File "<__array_function__ internals>", line 5, in inv
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/conda/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

**Comment by julienguy** [comment]
All fibers are masked (see "56 sky fibers discarded (because ivar=0 or bad FIBERSTATUS), only 0 left." above). All 500 fibers have fiberstatus bit BADAMPR.

**Comment by julienguy** [comment]
R4A is flagged as BADAMP because of the CTE issue. R4B is also flagged because of a transient variation of the bias level over several rows automatically detected leading to a OSTEP=12. So there are no fiber left for this camera. I am going to make minor changes to the sky subtraction code to return an error and throw an exception with a more meaningful message.
