### ISSUE TITLE
NightlyQA Crash in create_petalnz_pdf

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1548]
There was a failure in the QA plotting code when run on the night 20211220 in the daily specprod. 

Command run:
`desi_night_qa -p daily -n 20211220 -o /global/cfs/cdirs/desi/spectro/redux/daily/nightqa/20211220`

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_night_qa", line 155, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_night_qa", line 144, in main
    create_petalnz_pdf(outfns["petalnz"], args.night, args.prod, unq_tileids, unq_surveys, dchi2_threshold=25)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/night_qa.py", line 909, in create_petalnz_pdf
    "dark" : np.unique(ds["dark"]["TILEID"][ds["dark"]["SURVEY"] == survey]).size,
TypeError: list indices must be integers or slices, not str
```

**Comment by akremin** [comment]
Resolved with #1549
