### ISSUE TITLE
create_petalnz_pdf crash on 20211222

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1552]
New crash in Nightly QA in `create_petalnz_pdf`:

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_night_qa", line 155, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_night_qa", line 144, in main
    create_petalnz_pdf(outfns["petalnz"], args.night, args.prod, unq_tileids, unq_surveys, dchi2_threshold=25)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/night_qa.py", line 907, in create_petalnz_pdf
    ntiles_surv = {
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/night_qa.py", line 909, in <dictcomp>
    ds[faprgrm]["TILEID"][ds["bright"]["SURVEY"] == survey]
  File "astropy/table/_column_mixins.pyx", line 74, in astropy.table._column_mixins._ColumnGetitemShim.__getitem__
  File "astropy/table/_column_mixins.pyx", line 57, in astropy.table._column_mixins.base_getitem
  File "astropy/table/_column_mixins.pyx", line 69, in astropy.table._column_mixins.column_getitem
IndexError: boolean index did not match indexed array along dimension 0; dimension is 19936 but corresponding boolean dimension is 9041
```

Command run:
`desi_night_qa -p daily -n 20211222 -o /global/cfs/cdirs/desi/spectro/redux/daily/nightqa/20211222`

**Comment by akremin** [comment]
Fixed with PR #1554
