### ISSUE TITLE
tile-qa plotting crash night 20220101 tiles 1687 and 23321

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1563]
On 20220101, qa plots for tiles 1687 and 23321 crashed with:

```
desi_tile_qa -n 20220101 -t 1687
...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 216, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 158, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 66, in func
    figfile = make_tile_qa_plot(outfile, specprod_dir)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/tile_qa_plot.py", line 981, in make_tile_qa_plot
    plot_cutout(ax, hdr["TILEID"], hdr["TILERA"], hdr["TILEDEC"], 4)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/tile_qa_plot.py", line 326, in plot_cutout
    width_pix = img.shape[0]
IndexError: tuple index out of range
```
the full log is at /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/1687/20220101/logs/tile-qa-1687-thru20220101.log

@araichoor please investigate.  Thanks.

**Comment by araichoor** [comment]
I'm not sure why that is happening: my understanding is that the cutout query from legacysurvey failed, as reported in the log.
but in that case, the `img` variable should be an image with zeros, with the correct structure:
https://github.com/desihub/desispec/blob/e00de4809a1138c446c104208e2e356f75d87e95/py/desispec/tile_qa_plot.py#L265-L275

That is why I don't understand this error.
The cutout being not available already happened, without producing an error, e.g. few weeks ago:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/41975/20211212/tile-qa-41975-thru20211212.png

Re-running the command works fine (as the issue with the legacysurvey was temporary):
```
python -c "from desispec.tile_qa_plot import make_tile_qa_plot; make_tile_qa_plot('/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/1687/20220101/tile-qa-1687-thru20220101.fits', '/global/cfs/cdirs/desi/spectro/redux/daily', pngoutfile='tile-qa-1687-thru20220101.png')"
python -c "from desispec.tile_qa_plot import make_tile_qa_plot; make_tile_qa_plot('/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23321/20220101/tile-qa-23321-thru20220101.fits', '/global/cfs/cdirs/desi/spectro/redux/daily', pngoutfile='tile-qa-23321-thru20220101.png')"
```

I can investigate later if this happens again (though not trivial to do, as the cutout query usually failure usually is temporary, and works later).

**Comment by sbailey** [comment]
Thanks for the quick look.  I have rerun desi_tile_qa to generate the official daily tile qa plots for the missing tiles so this isn't urgent to debug today.

I agree this error is odd; it looks like a new problem where the viewer cutout is getting a zero-dimensional image but not completely failing.

Since the cutouts have been a source of fragility in the past, let's add a higher level try/except around `plot_cutout` in `make_tile_qa_plot`, while still printing the full traceback if something goes wrong, e.g. something like:
```python
try:
    plot_cutout(ax, hdr["TILEID"], hdr["TILERA"], hdr["TILEDEC"], 4)
except Exception as err:
    import sys, traceback
    lines = traceback.format_exception(*sys.exc_info())
    log.error('plot_cutout raised an exception:')
    print('\n'.join(lines))
    log.warning('continuing plotting without image cutout')
```

(try purposefully causing an exception in `plot_cutout` to make sure that actually works to print a meaningful traceback exception and move on)

**Comment by araichoor** [comment]
Thanks for the suggested lines to add: I can make a PR with "dummyly" copying those lines - I'm not familiar with those try/except/traceback commands.

Just one suggestion: maybe add this higher level try/except around the call to get_viewer_cutout(), which queries the legacysurvey? so that we would still have the EBV contours if that call fails; as far as I know, the fragility is in this cutout query with `wget`.
Something like:
```
pixscale = 10
size = int(width_deg * 3600.0 / pixscale)
img = np.zeros((size, size, 3))
try:
    img = get_viewer_cutout(
        tileid, tilera, tiledec, width_deg=width_deg, pixscale=10, dr="dr9", timeout=15,
    )
except Exception as err:
    import sys, traceback
    lines = traceback.format_exception(*sys.exc_info())
    log.error('get_viewer_cutout raised an exception:')
    print('\n'.join(lines))
    log.warning('continuing plotting without image cutout')
```

**Comment by sbailey** [comment]
We could sprinkle try/except at multiple levels.  I like the idea of getting the E(B-V) contours even if the cutout fails, but if I understand the original crash, `get_viewer_cutout` itself didn't raise an exception, but somehow returned a zero-dimensioned `img`, so a try/except there would not have caught that particular failure.  Perhaps get_viewer_cutout should also check the size or dimensionality of the image read from the jpeg-cutout return?

Regardless, the goal is to add another level of robutness that failing to make one subplot shouldn't prevent it from making the others.

**Comment by araichoor** [comment]
For info, the merged PR https://github.com/desihub/desispec/pull/1577 seems to have correctly fix such cases (also reported in issue https://github.com/desihub/desispec/issues/1576).
e.g. https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23708/20220109/logs/tile-qa-23708-thru20220109.log:

```
INFO:tile_qa_plot.py:274:get_viewer_cutout: no cutout from viewer after 15s, stopping the wget call
WARNING:tile_qa_plot.py:300:get_viewer_cutout: unexpected img.shape : () != (1440, 1440, 3) -> setting img = np.zeros((1440, 1440, 3))
INFO:desi_tile_qa:68:func: wrote QA plot /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23708/20220109/tile-qa-23708-thru20220109.png
```

Apparently, the issue is because the `img` is an empty np array with no shape; I still don't understand why is that, but at least it doesn't prevent anymore the code to proceed, and have a black cutout with the EBV contours:
https://data.desi.lbl.gov/desi/spectro/redux/daily/tiles/cumulative/23708/20220109/tile-qa-23708-thru20220109.png
