### ISSUE TITLE
Tile-qa Crash for Tile 23722 on 20220106

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#1576]
A crash in the tile-qa when generated a png (but not the fits file).

Log: /global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23722/20220106/logs/tile-qa-23722-thru20220106.log
```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 216, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 158, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/bin/desi_tile_qa", line 66, in func
    figfile = make_tile_qa_plot(outfile, specprod_dir)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/tile_qa_plot.py", line 981, in make_tile_qa_plot
    plot_cutout(ax, hdr["TILEID"], hdr["TILERA"], hdr["TILEDEC"], 4)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desispec/master/py/desispec/tile_qa_plot.py", line 326, in plot_cutout
    width_pix = img.shape[0]
IndexError: tuple index out of range
```

**Comment by araichoor** [comment]
Looks like same as discussed here: https://github.com/desihub/desispec/issues/1563, due likely to some glitch in legacysurvey.
Simply rerunning the command should work.
I'll make a PR with the change suggested in https://github.com/desihub/desispec/issues/1563.
Apologies for the trouble...

**Comment by akremin** [comment]
This happened both yesterday and this morning, but maybe I just got unlucky
or they are having an extended period of issues.

**Comment by araichoor** [comment]
Could be; my assumption is that it's because the wget querying the legacysurveys fails (reading your message, I was hoping it would still crash, so that I could diagnose more thoroughly the error, which I'm really understanding!).

But it works now:
```
python -c "from desispec.tile_qa_plot import make_tile_qa_plot; make_tile_qa_plot('/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/23722/20220106/tile-qa-23722-thru20220106.fits', '/global/cfs/cdirs/desi/spectro/redux/daily', pngoutfile='tile-qa-23722-thru20220106.png')"
```

**Comment by akremin** [comment]
It did work on the third try this morning, so apparently I was just unlucky before.

This happened again last night: Tile 25029, night 20220108.
Rerunning in the morning did work this time, however.

**Comment by araichoor** [comment]
Thanks for letting me know, and again sorry for the extra-work on your side.
I'll make the PR today, I'll have time.
