### ISSUE TITLE
Fuji: desi_tile_qa crash when some exps missing some cameras

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1664]
desi_tile_qa crashes when some of the input exposures are missing a camera but others have that camera.  e.g. tile 1 observed on 20210406 has all 30 cameras on exposures 83714 and 83715, but a z7 light staturation event on 83716 and so that frame was excluded from the processing.
```
source /global/homes/d/desi/bin/desi_fuji_env.sh
desi_tile_qa -n 20210406 -t 1 --group cumulative --outdir .
...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.4/bin/desi_tile_qa", line 267, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.4/bin/desi_tile_qa", line 196, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.4/bin/desi_tile_qa", line 62, in func
    fiberqa_table , petalqa_table = compute_tile_qa(night,tileid,specprod_dir,exposure_qa_dir,group=group)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.4/lib/python3.9/site-packages/desispec/tile_qa.py", line 71, in compute_tile_qa
    exposure_fiberqa_table , exposure_petalqa_table = compute_exposure_qa(night, expid, specprod_dir)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.4/lib/python3.9/site-packages/desispec/exposure_qa.py", line 309, in compute_exposure_qa
    scores = fitsio.read(cframe_filename,"SCORES")
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/fitsio/fitslib.py", line 139, in read
    with FITS(filename, **kwargs) as fits:
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/site-packages/fitsio/fitslib.py", line 520, in __init__
    self._FITS = _fitsio_wrap.FITS(filename, self.intmode, create)
OSError: FITSIO status = 104: could not open the named file
failed to find or open the following file: (ffopen)
/global/cfs/cdirs/desi/spectro/redux/fuji/exposures/20210406/00083716/cframe-z7-
00083716.fits
```

@araichoor can you make a branch off of the fuji branch and update desi_tile_qa to be robust to missing input frames?  In principle that is derivable from the exposure tables, but I think it would be acceptable to just trust other vetting to make sure that the frames that are supposed to exist do exist and let tile qa accept whatever it can find.  @akremin @julienguy please comment if you disagree.

**Comment by sbailey** [comment]
Fixed by #1665, but we need to rerun the missing tile-qa after the next tag.
