### ISSUE TITLE
tile-qa crash 80715 night 20210115 and 80718/20210130

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1687]
QA for tile 80715 on 20210115 and 80718/20210130 is crashing due to the following:
```
desi_tile_qa -n 20210115 -t 80715 --outdir .
...
ERROR:tile_qa.py:109:compute_tile_qa: could not identify prog
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_tile_qa", line 267, in <module>
    main()
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_tile_qa", line 196, in main
    entry = func(**func_arg)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/bin/desi_tile_qa", line 62, in func
    fiberqa_table , petalqa_table = compute_tile_qa(night,tileid,specprod_dir,exposure_qa_dir,group=group)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/0.51.8/lib/python3.9/site-packages/desispec/tile_qa.py", line 110, in compute_tile_qa
    raise ValueError("could not identify prog")
ValueError: could not identify prog
```

**Comment by sbailey** [comment]
See #1686 instead.

**Comment by araichoor** [comment]
The crash is at the step trying to recover or guess GOALTIME.
Those two tiles have the following fiberassign header values:
```
# TILEID FAFLAVOR TARG
80715 sv1m31 DESIROOT/target/catalogs/gaiadr2/0.48.0/targets/sv1/resolve/supp
80718 sv1rosette DESIROOT/target/catalogs/gaiadr2/0.50.0/targets/sv1/resolve/supp
```
Those  indeed are not handled by the current code, which uses the basename of TARG to guess the program.
I didn t handle this "supp" case.

I m not sure how to fix that.
Shall I just set GOALTIME=0 for any not-handled cases?
Or would it be even better to replace that part of the code with using the same recipe as in other places in desispec?
Those are listed here: https://github.com/desihub/desispec/issues/1649#issuecomment-1029513529

If useful, the exposures for those two tiles (from `/global/cfs/cdirs/desi/spectro/redux/fuji/exposures-fuji.fits`):
```
 NIGHT   EXPID TILEID      EXPTIME         EFFTIME_SPEC    GOALTIME MINTFRAC   SKY_MAG_R_SPEC  
 int32   int32 int32       float64           float64       float64  float64       float64      
-------- ----- ------ ----------------- ------------------ -------- -------- ------------------
#
20210115 72498  80715      900.04296875  768.1716918945312      0.0      0.9  21.15979279118737
20210115 72499  80715 900.0303344726562  701.9066162109375      0.0      0.9 21.133449396562614
20210115 72500  80715  900.039306640625 337.13275146484375      0.0      0.9  21.10905382123766
#
20210130 73720  80718 300.0876770019531  9.124605178833008      0.0      0.9 19.745111904124467
20210130 73721  80718 300.0907897949219   9.46870231628418      0.0      0.9 19.718588774760807
20210130 73727  80718 600.0631103515625  10.96377944946289      0.0      0.9 19.560143374976036
20210130 73728  80718 600.0503540039062  5.903741359710693      0.0      0.9 19.378241376920943
```
