### ISSUE TITLE
make desi_daily_proc_manager robust to sbatch failures

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1739]
Sometimes sbatch fails for a transient slurm reason, which currently crashes desi_daily_proc_manager.  We don't capture the log message from the failed sbatch, but an example traceback from 20220407 is:
```
INFO:procfuncs.py:372:create_batch_script: Outfile is: /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20220407/stdstarfit-20220407-00129064-a0123456789.slurm
INFO:util.py:528:parse_cameras: Converted input cameras=a0123456789 to camword=a0123456789
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/bin/desi_daily_proc_manager", line 151, in <module>
    daily_processing_manager(specprod=args.specprod, exp_table_path=args.exp_table_path,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/scripts/daily_processing.py", line 349, in daily_processing_manager
    = checkfor_and_submit_joint_job(ptable, arcs, flats, sciences, calibjobs,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/workflow/procfuncs.py", line 1163, in checkfor_and_submit_joint_job
    ptable, tilejob, internal_id = science_joint_fit(ptable, sciences, internal_id, z_submit_types=z_submit_types,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/workflow/procfuncs.py", line 994, in science_joint_fit
    return joint_fit(ptable=ptable, prows=sciences, internal_id=internal_id, queue=queue, reservation=reservation,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/workflow/procfuncs.py", line 914, in joint_fit
    joint_prow = create_and_submit(joint_prow, queue=queue, reservation=reservation, joint=True, dry_run=dry_run,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/workflow/procfuncs.py", line 229, in create_and_submit
    prow = submit_batch_script(prow, reservation=reservation, dry_run=dry_run, strictly_successful=strictly_successful)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/workflow/procfuncs.py", line 457, in submit_batch_script
    current_qid = subprocess.check_output(batch_params, stderr=subprocess.STDOUT, text=True)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/conda/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sbatch', '--parsable', '--dependency=afterok:57118300', '/global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20220407/stdstarfit-20220407-00129064-a0123456789.slurm']' returned non-zero exit status 1.
```

If/when the subprocess sbatch command fails:
  * capture the stdout/stderr and print it for future debugging why sbatch failed
  * sleep for 60 seconds then retry the same command, raising an exception and stopping only if it fails twice

**Comment by sbailey** [comment]
happened again on 20220411 (this time on a fiberflat job).
