### ISSUE TITLE
tile_qa_plot: all fibers flagged by LOW_EFFTIME for incomplete tiles

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#1752]
Because of the recent inclusion of the `LOW_EFFTIME` flag in the `bad_qafstatus_mask`:
https://github.com/desihub/desispec/blob/aa49cfbf92dc039a2e7cc1dde87da541398b528a/py/desispec/data/qa/qa-params.yaml#L40
done in PR https://github.com/desihub/desispec/pull/1722,

when a tile is not completed yet, all fibers are flagged as bad.
this makes the `tile_qa_plot.make_tile_qa_plot()` routine crash.

For instance `/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/10788/20220425/logs/tile-qa-10788-thru20220425.log`:
```
...
ERROR:desi_tile_qa:107:_wrap_make_tile_qa_plot: make_tile_qa_plot raised an exception:
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/bin/desi_tile_qa", line 102, in _wrap_make_tile_qa_plot
    figfile = make_tile_qa_plot(qafitsfile, specprod_dir)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/master/py/desispec/tile_qa_plot.py", line 1294, in make_tile_qa_plot
    nqso_rr = int(zhists[sel].sum() * istracer.sum())
ValueError: cannot convert float NaN to integer
```

The crash is at the step of computing `nn_qsorr`.

A simple fix is to add a "if ... else..." checking for that case, which would just keep `nqso_rr = 0`:
```
                if istracer.sum() == 0:
                    log.warning("istracer.sum() == 0 for QSO, probably due to LOW_EFFTIME (TBC); nqso_rr = 0")
                else:
                    nqso_rr = int(zhists[sel].sum() * istracer.sum())
```
That allows the code to finish, and to produce a plot like this:
![tile-qa-10788-thru20220425](https://user-images.githubusercontent.com/61986357/165357391-fcdbafbd-f3ee-4269-84c7-e50a9f6f1c29.png)

Would we be satisfied this simple fix? (@julienguy)

A minor drawback is that, as all fibers will be red (=flagged) for any uncompleted tile, it will prevent to identify potential issues on those; we would see the potential issues only when the tile will be completed (then most of fibers shouldn t be flagged with `LOW_EFFTIME`).

**Comment by araichoor** [comment]
Thanks.
A precision, thinking a bit further: in any case, for the xy plot with EFFTIME, the LOWEFFTIME fibers are highlighted in red (ie. that is independent of the addition of `LOWEFFTIME` to `bad_qafstatus_mask`.
So the only "new thing" is for the Z vs. FIBER plot, where everything is displayed in red now; and also the stats in the top-left part, which are now set to zero.
