### ISSUE TITLE
biasnight crash on 20210629

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1867]
Himalayas is crashing on the nightly biases for 20210629:
```
>>> import desispec.scripts.nightly_bias
>>> desispec.scripts.nightly_bias.main(['-n', '20210629', '-c', 'a0123456789'])
...
INFO:ccdcalib.py:506:select_zero_expids: Only 0 Calib ZEROS on 20210629 and cam z9, but want 23. Trying non-calibrations zeros
INFO:ccdcalib.py:528:select_zero_expids: Succeeded in adding 23 non-calib zeros. We now have 23 ZEROS on 20210629 and cam z9.
INFO:ccdcalib.py:600:compute_nightly_bias: Using 23 ZEROs for nightlybias 20210629 and cam z9
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/main/py/desispec/scripts/nightly_bias.py", line 45, in main
    compute_nightly_bias(**args.__dict__, comm=comm)
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/main/py/desispec/ccdcalib.py", line 631, in compute_nightly_bias
    rawfiles=[io.findfile('raw', night, e) for e in expids]
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/main/py/desispec/ccdcalib.py", line 631, in <listcomp>
    rawfiles=[io.findfile('raw', night, e) for e in expids]
  File "/global/common/software/desi/cori/desiconda/20211217-2.0.0/code/desispec/main/py/desispec/io/meta.py", line 319, in findfile
    filepath = os.path.normpath(location[filetype].format(**actual_inputs))
ValueError: Unknown format code 'd' for object of type 'float'
```

@akremin please check if this is a corner case we missed in your non-calibzeros fallback PR #1840

**Comment by sbailey** [comment]
Fixed via PR #1868.  Closing.
