### ISSUE TITLE
stdstar crash due to photsys=G targets

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#1892]
This stdstar fit crashes:
```
desi_fit_stdstars --delta-color 0.1 \
--frames /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/p8r/exposures/20210222/00077579/frame-[brz]9-00077579.fits.gz \
--skymodels /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/p8r/exposures/20210222/00077579/sky-[brz]9-00077579.fits.gz \
--fiberflats /global/cfs/cdirs/desi/spectro/desi_spectro_calib/trunk/spec/sm3/fiberflatnight-b9-20201214.fits \
  /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/p8r/calibnight/20210222/fiberflatnight-r9-20210222.fits \
  /global/cfs/cdirs/desi/users/sjbailey/spectro/redux/p8r/calibnight/20210222/fiberflatnight-z9-20210222.fits \
--starmodels /global/cfs/cdirs/desi/spectro/templates/basis_templates/v3.2/stdstar_templates_v2.2.fits  \
--outfile $SCRATCH/stdstars-9-00077579.fits.gz
...
Traceback (most recent call last):
  File "/global/common/software/desi/users/sjbailey/desispec2/bin/desi_fit_stdstars", line 21, in <module>
    sys.exit(stdstars.main(args))
  File "/global/common/software/desi/users/sjbailey/desispec2/py/desispec/scripts/stdstars.py", line 543, in main
    r_band = extinction_total_to_selective_ratio(band , photsys) # dimensionless
  File "/global/common/software/desi/perlmutter/desiconda/20220119-2.0.1/code/desiutil/main/py/desiutil/dust.py", line 92, in extinction_total_to_selective_ratio
    return R["{}_{}".format(band.upper(),photsys.upper())]
KeyError: 'R_G'
```

I'm not sure how we didn't trip on this before, but this comes from line 537+ of scripts/stdstars.py:
```
    photometric_systems = np.unique(fibermap['PHOTSYS'])
    if not gaia_std:
        for band in ['G', 'R', 'Z']:
            star_mags[band] = 22.5 - 2.5 * np.log10(fibermap['FLUX_'+band])
            star_unextincted_mags[band] = np.zeros(star_mags[band].shape)
            for photsys in  photometric_systems :
                r_band = extinction_total_to_selective_ratio(band , photsys) # dimensionless
...
```
i.e. even though we're not using Gaia stdstars, the presence of any photsys='G' targets in the fibermap is triggering requesting extinction for bands G, R, Z in the Gaia photometric system, `but desiutil.dust. extinction_total_to_selective_ratio` only knows about bands G, BP, and BR, not R or Z.

@julienguy could you investigate and fix?

**Comment by julienguy** [comment]
this is solved
