### ISSUE TITLE
coadd_cameras and compute_coadd_scores 

### ISSUE THREAD

**Issue by araichoor** [desihub/desispec#2088]
unless I am mis-using the code as I m not familiar with it -- in which case apologies -- it looks to me that there s an inconsistency here in `desispec.coaddition.coadd_cameras()`:
https://github.com/desihub/desispec/blob/f1293d27ba9d23b65cbc7124c35bdb5b7b22196d/py/desispec/coaddition.py#L721-L740

because, when `compute_coadd_scores` is called, `res.scores=None`, and because of that `compute_coadd_scores` will fill `res.scores` with the dictionary it s using, not updating a Table:
https://github.com/desihub/desispec/blob/cfdbdab7444dbaaba6fd49ed813663ebbe401793/py/desispec/specscore.py#L84-L91

and having `scores` has a dictionary can break things downstream.

context:
my goal is to (1) take a coadd, (2) coadd the cameras, (3) select some rows.
the step (3) crashes in `Spectra._get_slices`, as it expects `scores` to be a Table.

see code snippet below.

```
from desispec.io import read_spectra
from desispec.coaddition import coadd_cameras

fn = "/global/cfs/cdirs/desi/spectro/redux/iron/healpix/main/dark/0/0/coadd-main-dark-0.fits"
s = read_spectra(fn)        # s.scores is a Table
s_brz = coadd_cameras(s)    # s_brz.scores is a dictionary
tids = s_brz.fibermap["TARGETID"][:5]
s_brz_cut = s_brz.select(targets=tids)
```
returns:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/spectra.py", line 375, in select
    sp = self._get_slice(keep_rows, bands=keep_bands)
  File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/spectra.py", line 318, in _get_slice
    for col in self.scores.dtype.names:
AttributeError: 'dict' object has no attribute 'dtype'

```

**Comment by araichoor** [comment]
for what is worth, if my diagnosis above is correct, a simple workaround could be to replace this line:
https://github.com/desihub/desispec/blob/cfdbdab7444dbaaba6fd49ed813663ebbe401793/py/desispec/specscore.py#L90
by:
```
            # convert the dictionary to a table before feeding into coadd
            tabscores = astropy.table.Table()                                                                                                                                          
            for key in scores:
                tabscores[key] = scores[key]
            coadd.scores = tabscores
```
