### ISSUE TITLE
Tileqa crashes with missing EFFTIME header for 2021 data

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#2095]
Tileqa crashed for a specific backup tile: 41710 on 20230811.

It appears to be lack of a header keyword in one of the required files. Here is the traceback:

```
CRITICAL:util.py:153:runcmd: FAILED rank 0 exception while running desispec.scripts.tileqa.main(['-g', 'cumulative', '-n', '20230811', '-t', '41710']) called from line 622 in /global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/zproc.py
ERROR:util.py:161:runcmd: Traceback (most recent call last):
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/util.py", line 144, in runcmd
    result = cmd(*args)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/tileqa.py", line 227, in main
    _wrap_make_tile_qa_plot(qafitsfile, specprod_dir=args.prod)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/tileqa.py", line 114, in _wrap_make_tile_qa_plot
    figfile = make_tile_qa_plot(qafitsfile, specprod_dir)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/tile_qa_plot.py", line 1276, in make_tile_qa_plot
    exps = get_expids_efftimes(tileqafits, prod)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/tile_qa_plot.py", line 967, in get_expids_efftimes
    d["QA_EFFTIME_SPEC"][i] = fits.getheader(fn, "FIBERQA")["EFFTIME"]
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/header.py", line 169, in __getitem__
    card = self._cards[self._cardindex(key)]
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/astropy/io/fits/header.py", line 1819, in _cardindex
    raise KeyError(f"Keyword {keyword!r} not found.")
ERROR:util.py:161:runcmd: KeyError: "Keyword 'EFFTIME' not found."
CRITICAL:util.py:170:runcmd: FAILED desispec.scripts.tileqa.main(['-g', 'cumulative', '-n', '20230811', '-t', '41710'])
```

The code is combining data acquired back in 2021 (night=20211217 expid=114487). My guess is the data model has changed significantly enough that it breaks an assumption in tileqa.

**Comment by araichoor** [comment]
I can dig into that later (tonight/tomorrow).
in the meantime, from a quick investigation:
- other exposures from that night correctly have the `EFFTIME` keyword, e.g.:
```
raichoor@perlmutter:login24:~> fitsheader -e FIBERQA -k EFFTIME /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20211217/00114510/exposure-qa-00114510.fits 
# HDU FIBERQA in /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20211217/00114510/exposure-qa-00114510.fits:
EFFTIME =    131.1234588623047                                                  
```

- for whatever reason, the code refused to write the `EFFTIME` keyword for that exposure:
```
raichoor@perlmutter:login24:~> grep WARNING /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20211217/poststdstar-20211217-00114487-a0123456789-302597.log | grep EFFTIME
WARNING: Attribute `EFFTIME` of type <class 'numpy.float32'> cannot be added to FITS Header - skipping [astropy.io.fits.convenience]
```

also, don t know if that s relevant, note that this exposure from 20211217, has been processed on Feb. 21 and 24, 2023.

**Comment by araichoor** [comment]
I don t remember what we ve eventually done with that one (@akremin?)
but that apparently also happened for TILEID=42957, for EXPID=118314 on NIGHT=20220112:
```
tileid = 42957

d = Table.read("/global/cfs/cdirs/desi/spectro/redux/daily/exposures-daily.csv")
ii = np.where(d["TILEID"] == tileid)[0]
for i in ii:
    fn = "/global/cfs/cdirs/desi/spectro/redux/daily/exposures/{}/{:08d}/exposure-qa-{:08d}.fits".format(d["NIGHT"][i], d["EXPID"][i], d["EXPID"][i])
    hdr = fits.getheader(fn, "FIBERQA")
    if "EFFTIME" in hdr:
        print(fn, "\t", hdr["EFFTIME"])
    else:
        print(fn, "\t", "no EFFTIME")
```
returns:
```
/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/exposure-qa-00118314.fits 	 no EFFTIME
/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20221108/00152390/exposure-qa-00152390.fits 	 6.011321544647217
/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230126/00164810/exposure-qa-00164810.fits 	 8.144096374511719
/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230127/00164945/exposure-qa-00164945.fits 	 13.13466930389404
/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230128/00165074/exposure-qa-00165074.fits 	 12.80406188964844
/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230129/00165212/exposure-qa-00165212.fits 	 6.275713443756104
```

then:
```
raichoor@perlmutter:login12:~> grep WARNING /global/cfs/cdirs/desi/spectro/redux/daily/run/scripts/night/20220112/poststdstar-20220112-00118314-a0123456789-265087.log | grep EFFTIME
WARNING: Attribute `EFFTIME` of type <class 'numpy.float32'> cannot be added to FITS Header - skipping [astropy.io.fits.convenience]
```

note that the exposure from 20230930 (expid=98805) looks ok:
```
raichoor@perlmutter:login12:~/Scripts> fitsheader -e FIBERQA -k EFFTIME /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230930/00198805/exposure-qa-00198805.fits
# HDU FIBERQA in /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20230930/00198805/exposure-qa-00198805.fits:
EFFTIME =    6.172467231750488                                                  
```

pinging @abhi0395.

**Comment by araichoor** [comment]
small follow-up on expid=118314 from 20220112:
if I manually re-run the related lines:

https://github.com/desihub/desispec/blob/34b60836b98ea74151b4413955ee42cb2846e1d2/py/desispec/exposure_qa.py#L401-L409)

it seems to work (even if `EFFTIME~2s`); so I don t know what s happening, sorry...
```
from desispec.maskbits import fibermask
from desispec.exposure_qa import get_qa_params

qa_params = get_qa_params()["exposure_qa"]

fn = "/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/exposure-qa-00118314.fits"
fiberqa_table = Table.read(fn, "FIBERQA")
petalqa_table = Table.read(fn, "PETALQA")

bad_fibers_mask = fibermask.mask(qa_params["bad_qafstatus_mask"])
good_fibers = np.where((fiberqa_table['QAFIBERSTATUS']&bad_fibers_mask)==0)[0]
good_petals = np.unique(fiberqa_table['PETAL_LOC'][good_fibers])

fiberqa_table.meta['EFFTIME']=np.mean(petalqa_table['EFFTIME_SPEC'][good_petals])
```

**Comment by sbailey** [comment]
This smells related to #1978, where NaN values in TSNR2 resulted in those same EFFTIME warning messages and missing keyword.  That exact case was fixed by PR #2053, but that was after this 2021 / 2022 data that @araichoor is looking at.

@abhi0395 for the case you posted in desihub/desisurveyops#146 (tile 42957 on 20230930 exp 198805) it looks like it is also combining data from 2022, before the fix:
```
TILEID  NIGHT   EXPID 
------ -------- ------
 42957 20220112 118314
 42957 20221108 152390
 42957 20230126 164810
 42957 20230127 164945
 42957 20230128 165074
 42957 20230129 165212
 42957 20230930 198805
 42957 20231001 199013
```

As a backup tile, we may not need this QA, but if we do, I think the fix would be:
* verify that the earlier data has NaN values in some TSNR2* columns in the cframe SCORES HDU
* if so, reprocess those exposures

**Comment by araichoor** [comment]
raahh.. you re right; my test above again tripped on `Table.read()` converting nan's to masked.. what a pain.

if I replace `Table.read()` by `Table(fitsio.read())` in the code snippet I posted above, I then get `np.mean(petalqa_table['EFFTIME_SPEC'][good_petals]) = nan`, not ~2s.

and running the same code snippet as in #1978, it s the fibers 0 and 1 on the z-camera which are the issue, i.e. very similar to what s reported in #1978:

```
def _process_fn(fn):
    camera = fits.getheader(fn,0)["CAMERA"][0]
    key = "TSNR2_LRG_{}".format(camera.upper()) # I just check TSNR2_LRG, assuming the issue is independent of the TNSR2 column
    xs = fitsio.read(fn, "SCORES", columns=[key])[key]
    if not np.isfinite(xs.mean()):
        print(os.path.basename(fn), ",".join(np.where(~np.isfinite(xs))[0].astype(str)))

fns = sorted(glob("/global/cfs/cdirs/desi/spectro/redux/daily/exposures/20220112/00118314/cframe-*"))
for fn in fns:
    _process_fn(fn)
```
returns:
```
cframe-z0-00118314.fits.gz 0,1
```

**Comment by akremin** [comment]
@araichoor Now that the underlying code is fixed, could we add a patch to tileqa to make it robust to this? I'm thinking something useful so that we see there are nan's, but something that doesn't crash.

We can make this only true for backup tiles if we want, but I'm basically trying to avoid us reprocessing a bunch of backup tiles from 2 years ago.

For printing efftime I could imagine something like `outstr = f"efftime = {np.sum(efftimes[~np.isnan(efftimes)]} + {np.sum(np.isnan(efftimes))} nan's"`

For actual values in the files, maybe nan's are appropriate? Unless that will break other things further downstream

**Comment by araichoor** [comment]
mmhh.. 

first, I hear you that s it could feel a waste of your time to re-process 2+ yrs old backup tiles.

though, the efftime_spec is quite a critical column, so my 2 cents would be to keep it this way, so that we really see when nan's show up in efftime_spec.
for those cases, we know it s harmless, but there could be another failure mode that appear in the future, and we would just not see it if we protect against that.

as you say, one option could be to protect for that only for mainbackup tiles -- though note that this did happen for two bright tiles.

another option could be to fix+reprocess the exposures/tiles I list in https://github.com/desihub/desispec/issues/1978#issuecomment-1747592439.
as I see that @sbailey said there that the underlying issue is fixed, fixing the cases I list should get us in a clean state with no code change.

I d rather vote for the latter, but I d defer to the data team (and I can take care of the code change in exposure_qa.py if need be).

**Comment by schlafly** [comment]
FWIW, I'm with Anand that EFFTIME_SPEC is pretty critical for planning purposes.

If we had some other policy along the lines of "replace daily data with iron data" or something that would eventually fix all of these, I'd be happy waiting there and getting them all at once.  But I don't think we want the NaNs in the daily product indefinitely.
