### ISSUE TITLE
nightlyflat failing for 20231021 and 20231022 citing LinAlgError

### ISSUE THREAD

**Issue by abhi0395** [desihub/desispec#2131]
For nights 20231021 and 20231022, nightlyflat is failing, citing LinAlgError; therefore, they still remain unprocessed. I tried to dig into the issue a bit and found the following.

First, I checked that flats were executed successfully for both nights.

 ```
$ grep "SUCCESS: done at" flat-20231021-*.log
flat-20231021-00201975-a0123456789-17261980.log:SUCCESS: done at Sun 22 Oct 2023 01:28:34 PM PDT
flat-20231021-00201976-a0123456789-17261982.log:SUCCESS: done at Sun 22 Oct 2023 01:28:27 PM PDT
flat-20231021-00201977-a0123456789-17261986.log:SUCCESS: done at Sun 22 Oct 2023 01:28:37 PM PDT
flat-20231021-00201980-a0123456789-17261989.log:SUCCESS: done at Sun 22 Oct 2023 01:28:21 PM PDT
flat-20231021-00201981-a0123456789-17261990.log:SUCCESS: done at Sun 22 Oct 2023 01:28:28 PM PDT
flat-20231021-00201982-a0123456789-17261991.log:SUCCESS: done at Sun 22 Oct 2023 01:35:27 PM PDT
flat-20231021-00201985-a0123456789-17261993.log:SUCCESS: done at Sun 22 Oct 2023 01:36:42 PM PDT
flat-20231021-00201986-a0123456789-17261995.log:SUCCESS: done at Sun 22 Oct 2023 01:35:32 PM PDT
flat-20231021-00201987-a0123456789-17261996.log:SUCCESS: done at Sun 22 Oct 2023 01:35:57 PM PDT
flat-20231021-00201990-a0123456789-17261998.log:SUCCESS: done at Sun 22 Oct 2023 01:35:50 PM PDT
flat-20231021-00201991-a0123456789-17261999.log:SUCCESS: done at Sun 22 Oct 2023 01:51:49 PM PDT
flat-20231021-00201992-a0123456789-17262000.log:SUCCESS: done at Sun 22 Oct 2023 01:42:43 PM PDT
flat-20231021-00201993-a0123456789-17262003.log:SUCCESS: done at Sun 22 Oct 2023 01:41:46 PM PDT
```

```
$ grep "SUCCESS: done at" flat-20231022-*.log
flat-20231022-00202063-a0123456789-17268878.log:SUCCESS: done at Sun 22 Oct 2023 05:28:02 PM MST
flat-20231022-00202064-a0123456789-17268884.log:SUCCESS: done at Sun 22 Oct 2023 05:28:41 PM MST
flat-20231022-00202065-a0123456789-17268888.log:SUCCESS: done at Sun 22 Oct 2023 05:27:51 PM MST
flat-20231022-00202068-a0123456789-17268893.log:SUCCESS: done at Sun 22 Oct 2023 05:27:49 PM MST
flat-20231022-00202069-a0123456789-17268901.log:SUCCESS: done at Sun 22 Oct 2023 05:27:53 PM MST
flat-20231022-00202070-a0123456789-17268908.log:SUCCESS: done at Sun 22 Oct 2023 05:35:42 PM MST
flat-20231022-00202073-a0123456789-17268911.log:SUCCESS: done at Sun 22 Oct 2023 05:35:56 PM MST
flat-20231022-00202074-a0123456789-17268914.log:SUCCESS: done at Sun 22 Oct 2023 05:34:50 PM MST
flat-20231022-00202075-a0123456789-17268916.log:SUCCESS: done at Sun 22 Oct 2023 05:35:00 PM MST
flat-20231022-00202078-a0123456789-17268920.log:SUCCESS: done at Sun 22 Oct 2023 05:35:42 PM MST
flat-20231022-00202079-a0123456789-17268923.log:SUCCESS: done at Sun 22 Oct 2023 05:51:02 PM MST
flat-20231022-00202080-a0123456789-17268925.log:SUCCESS: done at Sun 22 Oct 2023 05:43:00 PM MST
flat-20231022-00202081-a0123456789-17268927.log:SUCCESS: done at Sun 22 Oct 2023 05:42:00 PM MST

```

Now the nightlyflat*.log files cite the following error:

https://data.desi.lbl.gov/desi/spectro/redux/daily/run/scripts/night/20231021/nightlyflat-20231021-00201975-a0123456789-17262005.log

```
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
CRITICAL:util.py:153:runcmd: FAILED rank 0 exception while running desispec.scripts.autocalib_fiberflat.main(['--night', '20231021', '--arm', 'r', '-i', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r0-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r0-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r0-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r0-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r1-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r1-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r1-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r1-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r2-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r2-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r2-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r2-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r3-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r3-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r3-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r3-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r4-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r4-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r4-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r4-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r5-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r5-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r5-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r5-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r6-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r6-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r6-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r6-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r7-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r7-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r7-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r7-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r8-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r8-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r8-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r8-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r9-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r9-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r9-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231021/tmp/fiberflatnight-camera-r9-lamp-3.fits']) called from line 357 in /global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/proc_joint_fit.py
ERROR:util.py:161:runcmd: Traceback (most recent call last):
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/util.py", line 144, in runcmd
    result = cmd(*args)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/autocalib_fiberflat.py", line 113, in main
    fiberflats = autocalib_fiberflat(inputs)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/fiberflat.py", line 630, in autocalib_fiberflat
    coeff, r, rank, s = np.linalg.lstsq(A, Z[:,j],rcond=-1)
ERROR:util.py:161:runcmd: File "<__array_function__ internals>", line 180, in lstsq
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2292, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 100, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
ERROR:util.py:161:runcmd: numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

```

https://data.desi.lbl.gov/desi/spectro/redux/daily/run/scripts/night/20231022/nightlyflat-20231022-00202063-a0123456789-17268931.log

```
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
CRITICAL:util.py:153:runcmd: FAILED rank 0 exception while running desispec.scripts.autocalib_fiberflat.main(['--night', '20231022', '--arm', 'r', '-i', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r0-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r0-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r0-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r0-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r1-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r1-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r1-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r1-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r2-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r2-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r2-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r2-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r3-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r3-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r3-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r3-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r4-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r4-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r4-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r4-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r5-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r5-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r5-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r5-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r6-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r6-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r6-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r6-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r7-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r7-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r7-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r7-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r8-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r8-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r8-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r8-lamp-3.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r9-lamp-0.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r9-lamp-1.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r9-lamp-2.fits', '/global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20231022/tmp/fiberflatnight-camera-r9-lamp-3.fits']) called from line 357 in /global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/proc_joint_fit.py
ERROR:util.py:161:runcmd: Traceback (most recent call last):
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/util.py", line 144, in runcmd
    result = cmd(*args)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/scripts/autocalib_fiberflat.py", line 113, in main
    fiberflats = autocalib_fiberflat(inputs)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/code/desispec/main/py/desispec/fiberflat.py", line 630, in autocalib_fiberflat
    coeff, r, rank, s = np.linalg.lstsq(A, Z[:,j],rcond=-1)
ERROR:util.py:161:runcmd: File "<__array_function__ internals>", line 180, in lstsq
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2292, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ERROR:util.py:161:runcmd: File "/global/common/software/desi/perlmutter/desiconda/20230111-2.1.0/conda/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 100, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
ERROR:util.py:161:runcmd: numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares
```

Now digging more into the scripts, it seems the problem is coming while `desispec.scripts.autocalib_fiberflat.main` is trying to call `desispec.fiberflat import autocalib_fiberflat`, which possibly tries to combine to create nightlyflat from those flats and uses some fitting functions.

https://github.com/desihub/desispec/blob/main/py/desispec/fiberflat.py#L629-L633

```
for j in range(nwave) :
       coeff, r, rank, s = np.linalg.lstsq(A, Z[:,j],rcond=-1)
       cfflat[ee][j] = coeff[0] # value at center of field of view
log.debug("median value at center of field for exp {} = {}".format(expid[i],np.median(cfflat[ee])))
```
Perhaps, the pipeline does not use `try and exception` when doing this fitting.

I also tried running `desispec.scripts.autocalib_fiberflat.main` with the same inputs on an interactive node to get more clean errors, but I received the same error.

**Comment by sbailey** [comment]
Some ideas to try:
* Visually inspect the unmasked values of the input fiberflats `plt.imshow(flat*(mask==0))` to look for unusual outliers, e.g. due to a new CCD hot column that isn't masked, or a very bad trace offset resulting in meaningless extracted flats.  (Related: is there anything unsual/new in the nightly darks?)
* Does the equivalent command on recent nights that used to work still work?  i.e. testing if something changed on the NERSC side.
* Using your own clone of desispec, wrap fiberflat.py line 630 `coeff, r, rank, s = np.linalg.lstsq(A, Z[:,j],rcond=-1)` with try/except, and in the except block add a checkpoint like `import IPython; IPython.embed()` and run interactively to inspect the values of `A` and `Z[:,j]` for values like NaN or Inf.  If present, trace upstream to find out where they are first introduced.

**Comment by akremin** [comment]
I have already been investigating bullet 2 -- when I sym-link the `exposures` and other `calibnight` calibrations (`badcol`, `bias`, `psfnight`) from the `daily` and run the nightlyflat code in my own specprod (`kremin`) it works for 20231019, but fails with the same error for 20231022.

I am currently running 20231018 and 20231022 from scratch in my specprod to see whether it is something in the input files that is causing the issue, and whether it is the code or corrupted files.

**Comment by akremin** [comment]
Update: rerunning 20231016 and 20231022 in a new specprod give an interesting result. Both night succeeded. In other words, I couldn't reproduce the issue.

This indicates an issue in the input flats or cals, which I checked with `fitsdiff`. All calibnight files were identical between the two prods. 11 of the 12 fiber* files in the exposures directory were identical, but one showed differences for all cameras (exposure 202079).

I currently have no explanation as to how the same code run twice on Perlmutter ~12 hours apart can lead to such differences in just 1 exposure out of 12. 

Another update is that 20231023 ran successfully. So this may be a transient issue that would be resolved by deleting the flats and reprocessing the affected nights.

**Comment by sbailey** [comment]
The 20231022 nightly flats are failing because daily/exposures/20231022/00202079/fiberflat-r?-00202079.fits.gz files have a bunch of NaN in them, which trace back to the extracted frames daily/exposures/20231022/00202079/frame-r?-00202079.fits.gz having NaNs.  However, the input preproc and psf files are fine, and when I rerun extractions on those I don't get NaNs either (i.e. same conclusion as @akremin, just a few steps earlier in the pipeline).  I don't see anything in the logs for why the frame files have NaN.  Ugh.

@abhi0395 please check all individual exposure fiberflats in 20231021 and try removing and rerunning those exposures.

e.g. for night 20231022 exposure 00202079 that would be
* delete daily/preproc/20231022/00202079 and daily/exposures/20231022/00202079
* sbatch daily/run/scripts/night/20231022/flat-20231022-00202079-a0123456789.slurm
* check daily/exposures/20231022/00202079/fiberflat-r?-00202079.fits.gz for NaNs.  If no NaNs, proceed.
* desi_resubmit_queue_failures -n 20231022

but let's try to fix 20231021 first so that any tiles that were observed on both 1021 and 1022 will get correct cumulative redshifts.

If NaN's reappear even with rerunning, post here again and we'll debug more.  Or if that recipe fails for some other reason, try removing the entire night and relaunching it.

**Comment by abhi0395** [comment]
@sbailey @akremin
Processing for 20231021 and 20231022 is complete now; tsnr+nightqa have been updated.
For 20231021: I followed the same steps and re-ran the affected exposure, and checked that there were no NaNs. However, it still failed in nightlyflat step. Then, I purged the night and re-processed it; it succeeded without any issues.
I have saved the nightlyflat*.log in `/global/cfs/cdirs/desi/spectro/redux/daily/run/nan_expid` 

For 1022, I just purged the night and re-processed it. There were some issues initially with the job submission, possibly due to the NERSC issue, but it was finally finished.

**Comment by sbailey** [comment]
@abhi0395 thanks.  On 20231021, which exposure had NaN?  Did you save the data with the NaNs, or just the logs?

I suspect that the missing step in my instructions was to remove the calibnight/20231021/tmp/*.fits files, but I'm glad that purging and rerunning the night worked.

**Comment by abhi0395** [comment]
@sbailey Yes, I have saved the NaN exposures for both 1021 (expid: 00201991) and 1022 (expid: 00202079) in the same directory: 
`/global/cfs/cdirs/desi/spectro/redux/daily/run/nan_expid`
