### ISSUE TITLE
sky test is failing in cholesky wrapper, but wrapper is missing docs and tests

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#30]
In the test_sky branch I added a simple compute_sky() test.  It is failing with an error inside desispec.linalg.cholesky_solve_and_invert():

    Traceback (most recent call last):
      File "/Users/sbailey/desi/git/desispec/py/desispec/test/test_sky.py", line 38, in test_uniform_resolution
        skyflux, skyivar, skymask = compute_sky(self.wave, flux, self.ivar, Rdata)
      File "/Users/sbailey/desi/git/desispec/py/desispec/sky.py", line 126, in compute_sky
      File "/Users/sbailey/desi/git/desispec/py/desispec/linalg.py", line 35, in cholesky_solve_and_invert
        raise Exception("covariance has NaN")
      Exception: covariance has NaN

The inputs do not have NaN, but that code has no docstring to guide what the inputs are supposed to be.  It is quite possible that the test itself has problematic input.

Please:
  * Add docstrings to the desispec.linalg functions so that we know what the inputs and outputs are supposed to be
  * Add some unit tests to confirm that they work
  * Get sky unit test working or punt it back to me if you think I'm doing something wrong

Note that cholesky_solve_and_invert has the line:

    inv,status=potri(L,lower=(not lower)) # 'not lower' is not a mistake, there is a BUG in scipy!!!!   

At some point (already?) that bug will get fixed and then this code will break, but we need a test to alert us when that happens...

**Comment by sbailey** [comment]
fixed with pull request #37
