### ISSUE TITLE
tests fail on as-installed desispec at NERSC

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#419]
desispec tests pass, but they don't pass on a copy of desispec as installed by desiInstall at NERSC. Although normally one runs tests before installing, it is still helpful to be able to run tests post-installation to verify that the as-installed copies of code work before doing a final signoff on a set of tags for a desimodules release. Most of our repos work with a post-install test; desiutil and desispec are the exceptions.

e.g.
```
source /project/projectdirs/desi/software/desi_environment.sh
cd $DESISPEC; python setup.py test
```
All the failures are in test_binscripts, with errors in the log like like
```
test_compute_fiberflat (desispec.test.test_binscripts.TestBinScripts) ... Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/code/desispec/0.15.1/bin/desi_compute_fiberflat", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.15.1', 'desi_compute_fiberflat')
  File "/global/common/cori/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/global/common/cori/contrib/desi/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1491, in run_script
pkg_resources.ResolutionError: No script named 'desi_compute_fiberflat'
```
However, desi_compute_fiberflat is in the PATH and in the bin/ directory where it would normally find it if testing prior to installation:
```
desi@cori17[1001]$ which desi_compute_fiberflat
/global/common/cori/contrib/desi/code/desispec/0.15.1/bin/desi_compute_fiberflat
desi@cori17[1004]$ ls bin/desi_compute_fiberflat 
bin/desi_compute_fiberflat*
```

Also see desihub/desiutil#78 which is also about tests not working on as-installed copies, though the symptoms are different in that case.

**Comment by weaverba137** [comment]
Please try running the test with
```
source /project/projectdirs/desi/software/desi_environment.sh
python -m desispec.test.desispec_test_suite
```

**Comment by sbailey** [comment]
Tests run and pass in that case, though they do start with the concerning error message:
```
/global/common/edison/contrib/desi/desiconda/20170613-1.1.4-
spectro/code/desiconda/20170613-1.1.4-spectro_conda/lib/python3.5/runpy.py:125:
RuntimeWarning: 'desispec.test.desispec_test_suite' found in sys.modules after import
of package 'desispec.test', but prior to execution of 'desispec.test.desispec_test_suite';
this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
```

**Comment by weaverba137** [comment]
Yes, I saw that, but that can be fixed by commenting out a line in the `test/__init__.py` file.  See https://github.com/desihub/desiutil/blob/master/py/desiutil/test/__init__.py

**Comment by sbailey** [comment]
This no longer works:
```
source /project/projectdirs/desi/software/desi_environment.sh 17.12
cd $HOME
python -m desispec.test.desispec_test_suite
```
But this does work:
```
source /project/projectdirs/desi/software/desi_environment.sh 17.12
cd $DESISPEC
python -m desispec.test.desispec_test_suite
```

In the former case, it is failing to find the installed script directory and creating the wrong path to the scripts to run:
```
test_compute_sky (desispec.test.test_binscripts.TestBinScripts) ... INFO:util.py:72:runcmd: Thu Jan 11 13:53:01 2018
2018-01-11 13:53:01,198 desiutil.log.dlm58.info INFO : Thu Jan 11 13:53:01 2018
INFO:util.py:73:runcmd: RUNNING: /global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/bin/python /global/u2/s/sjbailey/bin/desi_compute_sky --infile frame-3268c6293e504c09a87f3d36acfc7621.fits --fiberflat fiberflat-3268c6293e504c09a87f3d36acfc7621.fits --outfile sky-3268c6293e504c09a87f3d36acfc7621.fits --qafile qa-data-3268c6293e504c09a87f3d36acfc7621.yaml --qafig qa-3268c6293e504c09a87f3d36acfc7621.pdf
2018-01-11 13:53:01,198 desiutil.log.dlm58.info INFO : RUNNING: /global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/bin/python /global/u2/s/sjbailey/bin/desi_compute_sky --infile frame-3268c6293e504c09a87f3d36acfc7621.fits --fiberflat fiberflat-3268c6293e504c09a87f3d36acfc7621.fits --outfile sky-3268c6293e504c09a87f3d36acfc7621.fits --qafile qa-data-3268c6293e504c09a87f3d36acfc7621.yaml --qafig qa-3268c6293e504c09a87f3d36acfc7621.pdf
  Inputs
    frame-3268c6293e504c09a87f3d36acfc7621.fits
    fiberflat-3268c6293e504c09a87f3d36acfc7621.fits
  Outputs
    sky-3268c6293e504c09a87f3d36acfc7621.fits
    qa-data-3268c6293e504c09a87f3d36acfc7621.yaml
    qa-3268c6293e504c09a87f3d36acfc7621.pdf
/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/desiconda/20170613-1.1.4-spectro_conda/bin/python: can't open file '/global/u2/s/sjbailey/bin/desi_compute_sky': [Errno 2] No such file or directory
```
Note that it is looking for the `desi_compute_sky` script in my home bin/ directory instead of in the installation location.  The logic for finding the appropriate bin directory needs to be updated in `test_binscripts.TestBinScripts.setUpClass` (while not breaking its ability to work with pre-installed scripts too...)
