### ISSUE TITLE
QA doesn't work with matplotlib 2.1.0

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#447]
Travis tests using matplotlib 2.1.0 fail due to a variety of QA/matplotlib problems:
```
======================================================================
ERROR: test_exposure_fibermap_plot (desispec.test.test_qa.TestQA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/colors.py", line 132, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
TypeError: unhashable type: 'numpy.ndarray'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4050, in scatter
    colors = mcolors.to_rgba_array(c)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/colors.py", line 233, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/colors.py", line 134, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/colors.py", line 185, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: array([[ 0.81565074,  1.18969683,  0.98958279,  1.00012845,  0.99419769,
         0.99616498,  1.00463469,  1.00481815,  0.99791284,  1.00224492]])
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/desihub/desispec/py/desispec/test/test_qa.py", line 192, in test_exposure_fibermap_plot
    exposure_fibermap('b', self.expid, 'meanflux', outfile=self.exp_fmap_plot)
  File "/home/travis/build/desihub/desispec/py/desispec/qa/qa_plots.py", line 517, in exposure_fibermap
    outfile=outfile)
  File "/home/travis/build/desihub/desispec/py/desispec/qa/qa_plots.py", line 545, in exposure_map
    mplt = ax.scatter(x, y, marker='o', s=9., c=metric, cmap=jet)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4055, in scatter
    raise ValueError(msg.format(c.shape, x.size, y.size))
ValueError: c of shape (2, 1, 10) not acceptable as a color sequence for x with size 20, y with size 20
----------------------------------------------------------------------
```

These tests pass with matplotlib 2.0.2 .

Reproduce this outside of Travis (e.g. with a custom conda environment with matplotlib 2.1.0) and see if it is something we can/should fix on our end, or whether we need to submit a matplotlib bug report and skip version 2.1.0 .  For now, Travis tests are pinned to 2.0.

Any changes on our side should maintain compatibility with 2.0 because that is what we currently have installed in most places.

**Comment by profxj** [comment]
Travis now running with matplotlib 2.2.2
and all tests passing.
