### ISSUE TITLE
qadata broke desi_pipe create

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#639]
@profxj @tskisner running the desispec pipeline integration test `python -m desispec.test.integration_test` fails with:
```
Traceback (most recent call last):
  File "/Users/sbailey/desi/git/desispec/bin/desi_pipe", line 14, in <module>
    p = PipeUI()
  File "/Users/sbailey/desi/git/desispec/py/desispec/scripts/pipe.py", line 78, in __init__
    getattr(self, args.command)()
  File "/Users/sbailey/desi/git/desispec/py/desispec/scripts/pipe.py", line 281, in create
    pipe.update_prod(nightstr=None, hpxnside=args.nside)
  File "/Users/sbailey/desi/git/desispec/py/desispec/pipeline/prod.py", line 272, in update_prod
    db.update(nt, hpxnside, expid)
  File "/Users/sbailey/desi/git/desispec/py/desispec/pipeline/db.py", line 603, in update
    alltasks , healpix_frames = all_tasks(night, nside, expid=expid)
  File "/Users/sbailey/desi/git/desispec/py/desispec/pipeline/db.py", line 286, in all_tasks
    full["qadata"].append(props)
KeyError: 'qadata'
Traceback (most recent call last):
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sbailey/desi/git/desispec/py/desispec/test/integration_test.py", line 287, in <module>
    integration_test()
  File "/Users/sbailey/desi/git/desispec/py/desispec/test/integration_test.py", line 171, in integration_test
    sp.check_call(com, shell=True)
  File "/Users/sbailey/anaconda/envs/desi/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'desi_pipe create --db-sqlite' returned non-zero exit status 1
```
This appears to be caused by changes in PR #633 .  Please fix ASAP.

**Comment by julienguy** [comment]
I am on it

**Comment by julienguy** [comment]
a small bug is now fixed in master. I am running the integration test

**Comment by julienguy** [comment]
I successfully ran the integration test so I am closing this issue.
