### ISSUE TITLE
desi_pipe tasks failing

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#661]
`desi_pipe tasks` from the minitest is failing:
```
$> source /project/projectdirs/desi/software/desi_environment.sh test-master
$> source /global/cscratch1/sd/sjbailey/desi/dev/end2end/spectro/redux/mini/setup.sh
$> desi_pipe tasks --tasktype fiberflat --states ready,waiting
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/master/bin/desi_pipe", line 14, in <module>
    p = PipeUI()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/master/py/desispec/scripts/pipe.py", line 81, in __init__
    getattr(self, args.command)()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/master/py/desispec/scripts/pipe.py", line 248, in tasks
    taskfile=args.taskfile)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/master/py/desispec/pipeline/control.py", line 342, in tasks
    raise RuntimeError("Task state '{}' is not valid".format(s))
RuntimeError: Task state 'r' is not valid
```

@tskisner this is a blocking factor for the minitest and thus the 18.6 release.  Please fix at high priority.  Almost as high priority is fixing why this wasn't caught by the recently merged pipeline tests or desispec unit tests.

**Comment by tskisner** [comment]
Working on this.  As for why this was not caught, the pipeline integration tests only cover the "high-level" commands (e.g. desi_pipe chain, desi_night).  Test coverage on other pipeline commands definitely needs to be restored (see #534 ).  We should move that issue up in priority for the 18.9 release.

**Comment by tskisner** [comment]
This was a few-line problem left over from moving code from desi_pipe into desispec.pipeline.control.  I double checked that there were no other places like this.  I just pushed the fix directly to master.

**Comment by weaverba137** [comment]
Proceeding with the minitest notebook...

**Comment by weaverba137** [comment]
I didn't experience any problems running the pipeline in the notebook.  So I think this can be closed.
