### ISSUE TITLE
Checking on the correct use of SkySub_QP

### ISSUE THREAD

**Issue by Srheft** [desihub/desispec#694]
@julienguy :

* Quicklook tries to make sure not to lose the functionality of the qproc algorithms inside QL [i.e., replacing BoxcarExtract, ApplyFiberFlat_QL, SkySub_QL with Extract_QP, ApplyFiberFlat_QP, SkySub_QP]. The use of configuration you included here in https://github.com/desihub/desispec/pull/664  has been tried successfully up until 2 weeks ago. 

* Could you please repeat the same exact test you did in https://github.com/desihub/desispec/pull/664 with **master** with the configuration file you included there?   **desi_qproc** has no problem processing this exposure but quicklook fails at SkySub_QP.  My initial guess was that a parameter is simply not set correctly [hence the empty array]. Would appreciate if you double check.   

Running this in master:
**desi_quicklook -i qlconfig_darksurvey.yaml -n 20191001 -c b0 -e 3578**
I get:

`2018-09-13 02:22:33,835 QuickLook INFO : Running SkySub_QP
INFO:qsky.py:11:qproc_sky_subtraction: Starting...
2018-09-13 02:22:33,836 desiutil.log.dlm58.info INFO : Starting...
INFO:qsky.py:31:qproc_sky_subtraction: Sky fibers: [  4  38  52  55  59  64  71  83 145 157 163 172 173 184 189 204 222 239
 256 258 275 278 295 307 309 314 333 339 343 348 350 401 444 463 470]
2018-09-13 02:22:33,857 desiutil.log.dlm58.info INFO : Sky fibers: [  4  38  52  55  59  64  71  83 145 157 163 172 173 184 189 204 222 239
 256 258 275 278 295 307 309 314 333 339 343 348 350 401 444 463 470]
2018-09-13 02:22:33,863 QuickLook CRITICAL : Failed to run PA SkySub_QP error was array of sample points is empty
Traceback (most recent call last):
  File "/desi/software/desispec/py/desispec/quicklook/quicklook.py", line 285, in runpipeline
    inp=pa(inp,**pargs)
  File "/desi/software/desispec/py/desispec/quicklook/pas.py", line 18, in __call__
    return self.run(*args,**kwargs)
  File "/desi/software/desispec/py/desispec/quicklook/procalgs.py", line 1021, in run
    return self.run_pa(input_qframe,dumpfile=dumpfile)
  File "/desi/software/desispec/py/desispec/quicklook/procalgs.py", line 1025, in run_pa
    skymodel = qproc_sky_subtraction(qframe,return_skymodel=True)
  File "/desi/software/desispec/py/desispec/qproc/qsky.py", line 37, in qproc_sky_subtraction
    tflux[i]=np.interp(twave,qframe.wave[i,jj],qframe.flux[i,jj])
  File "/home/user/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2061, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty
Failed to run PA SkySub_QP
`

**Comment by julienguy** [comment]
I ran the following and did not get the errors you are reporting. I am running out of desispec master.
```
export QL_SPEC_DATA=/global/project/projectdirs/desi/spectro/data
export QL_CONFIG_DIR=/global/homes/j/jguy/software/desispec/py/desispec/data/quicklook
export QL_SPEC_REDUX=/project/projectdirs/desi/users/jguy/quicklook-test/qproc
time desi_quicklook -i /project/projectdirs/desi/users/jguy/quicklook-test/qproc_config.yaml -n 20191001 -c b0 -e 3578 &> qproc-b0.log &
```
the log file is there
```/project/projectdirs/desi/users/jguy/quicklook-test/qproc-b0.log```

I get the quicklook S/N fit crash that is discussed elsewhere  
```
WARNING:qalib.py:704:SNRFit: In fit of ELG, Fit minimization failed!
/global/common/software/desi/users/jguy/desispec/py/desispec/qa/qalib.py:615: RuntimeWarning: invalid value encountered in sqrt
  "astro":lambda x,a,b:(exptime*a*x)/np.sqrt(exptime*(a*x+b)+r2)
2018-09-13 13:45:43,201 desiutil.log.dlm58.info WARNING : In fit of ELG, Fit minimization failed!
WARNING:qalib.py:688:SNRFit: In fit of LRG, had to remove NANs from data for fitting!
2018-09-13 13:45:43,206 desiutil.log.dlm58.info WARNING : In fit of LRG, had to remove NANs from data for fitting!
WARNING:qalib.py:704:SNRFit: In fit of LRG, Fit minimization failed!
2018-09-13 13:45:43,240 desiutil.log.dlm58.info WARNING : In fit of LRG, Fit minimization failed!
2018-09-13 13:45:43,342 QuickLook WARNING : 1 objects have no or unphysical magnitudes

```
but not what you are reporting above.
