### ISSUE TITLE
fix extract.main_mpi for new fibermap

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#728]
The new fibermap format in desispec/ 0.26.0 broke the pipeline running spectral extractions (see traceback below).  Oddly:
* the integration test includes spectral extractions that don't fail (though via `desispec.scripts.extract.main` instead of `desispec.scripts.extract.main_mpi`).
* the failure is from trying to assign the string "TGT" to an element in a float array.  That string appears as a new OBJTYPE value, but none of the old OBJTYPE values (ELG, LRG, QSO...) would have been valid floats either.  So why didn't it crash before (cf. [schroedinbug](https://books.google.com/books?id=g80P_4v4QbIC&pg=PA397&dq=schroedinbug#v=onepage&q=schroedinbug&f=false))?

Fix this at high priority for the 18.12 release (or before!).

```
================= Process 0 =================
INFO:extract.py:318:main_mpi: extract:  input = /global/cscratch1/sd/desi/desi/spectro/redux/nightly/preproc/20191001/00003575/preproc-r3-00003575.fits
INFO:extract.py:319:main_mpi: extract:  psf = /global/cscratch1/sd/desi/desi/spectro/redux/nightly/exposures/20191001/00003575/psf-r3-00003575.fits
INFO:extract.py:320:main_mpi: extract:  specmin = 0
INFO:extract.py:321:main_mpi: extract:  nspec = 500
INFO:extract.py:322:main_mpi: extract:  wavelength = 5635.0,7731.0,0.8
INFO:extract.py:323:main_mpi: extract:  nwavestep = 50
INFO:extract.py:324:main_mpi: extract:  regularize = 0.0
INFO:extract.py:356:main_mpi: extract:  Rank 0 starting preproc-r3-00003575.fits spectra 0:25 at Thu Nov 15 21:40:12 2018
INFO:extract.py:416:main_mpi: extract:  Done preproc-r3-00003575.fits spectra 0:25 at Thu Nov 15 21:41:44 2018
ERROR:base.py:496:run: FAILED: task extract_20191001_r_3_00003575 process 0
ERROR:base.py:500:run: Traceback (most recent call last):
  File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/code/desispec/0.26.0/lib/python3.6/site-packages/desispec-0.26.0-py3.6.egg/desispec/pipeline/tasks/base.py", line 493, in run
    self._run(name, opts, comm, db)
  File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/code/desispec/0.26.0/lib/python3.6/site-packages/desispec-0.26.0-py3.6.egg/desispec/pipeline/tasks/extract.py", line 142, in _run
    extract.main_mpi(args, comm=comm)
  File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/code/desispec/0.26.0/lib/python3.6/site-packages/desispec-0.26.0-py3.6.egg/desispec/scripts/extract.py", line 450, in main_mpi
    mergebundles.main(mergeargs)
  File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/code/desispec/0.26.0/lib/python3.6/site-packages/desispec-0.26.0-py3.6.egg/desispec/scripts/mergebundles.py", line 101, in main
    fibermap[ii] = xfibermap
  File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 1360, in __setitem__
    col[item] = val
  File "/global/common/software/desi/edison/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/astropy/table/column.py", line 915, in __setitem__
    self.data[index] = value
ValueError: could not convert string to float: 'TGT'
```

**Comment by sbailey** [comment]
Update (don't panic): the problem was that I was testing with mockobs data, which used a slightly older fibermap than the latest format.  The merge bundles code was creating an empty fibermap data structure using the latest format, and then trying to shoehorn in a different format (mea culpa).  It would be better for merge bundles to derive the fibemap format from the input files rather than having a strict requirement on exactly what it must be.
