### ISSUE TITLE
allow extractions to go slightly off the edge of the CCD

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#833]
This might be a fix in desispec.scripts.extract, or it may require something in specter.

Night 20191024 exposure 20672 with OBSTYPE=FLAT got traceshifted slightly off of the default extraction wavelength range `-w 5635.0,7731.0,0.8` resulting in:
```
Traceback (most recent call last):
  File "/global/homes/s/sjbailey/bin/desi_proc", line 281, in <module>
    desispec.scripts.extract.main_mpi(extract_args, comm=comm_extract)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/scripts/extract.py", line 364, in main_mpi
    raise ValueError('Stop wavelength {:.2f} > max wavelength {:.2f} for these fibers'.format(wstop, psf_wavemax))
ValueError: Stop wavelength 5934.00 > max wavelength 5933.92 for these fibers
```

Update specter and/or desispec.scripts.extract to allow going slightly off the edge of the CCD, just filling in with flux=0 ivar=0 mask>0 and dummy resolution matrix elements.

**Comment by sbailey** [comment]
I disabled the checks and tested going off the PSF wavelength limits, and it worked.  It even works to go off by more than one PSF size.  Going way off doesn't work, which is probably triggered by having an entire divide-and-conquer subregion including its boundary zone being off the PSF coverage.  Check that in more detail.
