### ISSUE TITLE
fluxcalib crash 20200209/47944

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#877]
Track this down and fix.  There isn't anything obviously wrong in the raw data but I haven't chased it further than that.  Filing a ticket so that we remember to followup.
```
desi_compute_fluxcalibration --infile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200209/00047944/frame-r4-00047944.fits \
--sky /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200209/00047944/sky-r4-00047944.fits \
--fiberflat /global/cfs/cdirs/desi/spectro/redux/daily/calibnight/20200209/fiberflatnight-r4-20200209.fits \
--models /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200209/00047944/stdstars-4-00047944.fits \
--delta-color-cut 0.2 --min-color 0.25 --highest-throughput 4 \
--outfile /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200209/00047944/fluxcalib-r4-00047944.fits

...
INFO:fluxcalibration.py:994:compute_flux_calibration: iter 13 fit smooth correction per fiber
INFO:fluxcalibration.py:998:compute_flux_calibration: iter 13 fiber 0(smooth)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/polynomial.py:627: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
WARNING:fluxcalibration.py:1018:compute_flux_calibration: polynomial fit for fiber 2 failed

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
WARNING:fluxcalibration.py:1018:compute_flux_calibration: polynomial fit for fiber 3 failed

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
WARNING:fluxcalibration.py:1018:compute_flux_calibration: polynomial fit for fiber 4 failed
INFO:fluxcalibration.py:998:compute_flux_calibration: iter 13 fiber 10(smooth)

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
WARNING:fluxcalibration.py:1018:compute_flux_calibration: polynomial fit for fiber 10 failed

Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
WARNING:fluxcalibration.py:1018:compute_flux_calibration: polynomial fit for fiber 11 failed
INFO:fluxcalibration.py:1024:compute_flux_calibration: iter 13 rejecting
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/fluxcalibration.py:1067: RuntimeWarning: Mean of empty slice
  mean=1./np.nanmean(1./smooth_fiber_correction[ii][badfiber[ii]==0],axis=0)
INFO:fluxcalibration.py:1072:compute_flux_calibration: iter #13 chi2=4917.468481 ndf=6139 chi2pdf=0.801021 nout=0 mean=nan
INFO:fluxcalibration.py:946:compute_flux_calibration: iter 14 fiber 0
INFO:fluxcalibration.py:946:compute_flux_calibration: iter 14 fiber 10
INFO:fluxcalibration.py:972:compute_flux_calibration: iter 14 solving
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/bin/desi_compute_fluxcalibration", line 16, in <module>
    fluxcal.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/scripts/fluxcalibration.py", line 148, in main
    fluxcalib = compute_flux_calibration(frame, model_wave, model_flux, model_fibers%500, highest_throughput_nstars = args.highest_throughput)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/fluxcalibration.py", line 980, in compute_flux_calibration
    calibration[w]=cholesky_solve(A_pos_def, B[w])
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/linalg.py", line 28, in cholesky_solve
    X = scipy.linalg.cho_solve((UorL,lower),B)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 209, in cho_solve
    x, info = potrs(c, b1, lower=lower, overwrite_b=overwrite_b)
_flapack.error: (shape(c,0)==shape(b,0)) failed for 2nd argument b
```

**Comment by sbailey** [comment]
The original command using inputs from the daily prod still fails, but rerunning the entire exposure from the beginning with the latest calibs works fine, so closing ticket.
