### ISSUE TITLE
fix flux calibration crash

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#89]
desi_compute_fluxcalibration.py is crashing; it appears that is is having trouble finding the input standard star templates.  How templates are generated and read recently changed on the desisim side; this may be related.

This would be the top priority ticket except that this probably isn't needed for the Argonne workshop this week.  Argonne workshop needs get top priority, then this.

```
[edison ~] python -m pdb $DESISPEC/bin/desi_compute_fluxcalibration.py           --infile /scratch1/scratchdirs/sjbailey/desi/spectro/redux/dailytest/exposures/20151101/00000002/frame-b0-00000002.fits --fibermap /scratch1/scratchdirs/sjbailey/desi/spectro/sim/dailytest/20151101/fibermap-00000002.fits --fiberflat /scratch1/scratchdirs/sjbailey/desi/spectro/redux/dailytest/calib2d/20151101/fiberflat-b0-00000000.fits --sky /scratch1/scratchdirs/sjbailey/desi/spectro/redux/dailytest/exposures/20151101/00000002/sky-b0-00000002.fits           --models /scratch1/scratchdirs/sjbailey/desi/spectro/redux/dailytest/exposures/20151101/00000002/stdstars-sp0-00000002.fits --outfile /scratch1/scratchdirs/sjbailey/desi/spectro/redux/dailytest/exposures/20151101/00000002/fluxcalib-b0-00000002.fits
> /project/projectdirs/desi/software/edison/desispec/master/bin/desi_compute_fluxcalibration.py(9)<module>()
-> """
(Pdb) c
INFO:desi_compute_fluxcalibration.py:49:main: read frame
INFO:desi_compute_fluxcalibration.py:53:main: apply fiberflat
INFO:fiberflat.py:259:apply_fiberflat: starting
INFO:fiberflat.py:288:apply_fiberflat: done
INFO:desi_compute_fluxcalibration.py:60:main: subtract sky
INFO:sky.py:202:subtract_sky: starting
INFO:sky.py:214:subtract_sky: done
INFO:desi_compute_fluxcalibration.py:67:main: compute flux calibration
INFO:desi_compute_fluxcalibration.py:80:main: star fibers= [2]
INFO:fluxcalibration.py:212:compute_flux_calibration: starting
Traceback (most recent call last):
  File "/scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/python-2.7.9_d371bbbe-7.1/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/python-2.7.9_d371bbbe-7.1/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/python-2.7.9_d371bbbe-7.1/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/project/projectdirs/desi/software/edison/desispec/master/bin/desi_compute_fluxcalibration.py", line 9, in <module>
    """
  File "/project/projectdirs/desi/software/edison/desispec/master/bin/desi_compute_fluxcalibration.py", line 89, in main
    fluxcalib = compute_flux_calibration(frame, fibers, model_wave, model_flux)
  File "/project/projectdirs/desi/software/edison/desispec/master/py/desispec/fluxcalibration.py", line 225, in compute_flux_calibration
    model_flux[fiber]=resample_flux(stdstars.wave,input_model_wave,input_model_flux[fiber])
  File "/project/projectdirs/desi/software/edison/desispec/master/py/desispec/interpolation.py", line 130, in resample_flux
    return _unweighted_resample(xout, x, flux)
  File "/project/projectdirs/desi/software/edison/desispec/master/py/desispec/interpolation.py", line 195, in _unweighted_resample
    ty=np.interp(tx,ix,iy)
  File "/scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/numpy-1.9.2_a439d69e-7.1/lib/python2.7/site-packages/numpy/lib/function_base.py", line 1191, in interp
    return compiled_interp(x, xp, fp, left, right)
ValueError: object of too small depth for desired array
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /scratch1/scratchdirs/kisner/software/hpcports_shared_gnu/numpy-1.9.2_a439d69e-7.1/lib/python2.7/site-packages/numpy/lib/function_base.py(1191)interp()
-> return compiled_interp(x, xp, fp, left, right)
(Pdb) u
> /project/projectdirs/desi/software/edison/desispec/master/py/desispec/interpolation.py(195)_unweighted_resample()
-> ty=np.interp(tx,ix,iy)
(Pdb) u
> /project/projectdirs/desi/software/edison/desispec/master/py/desispec/interpolation.py(130)resample_flux()
-> return _unweighted_resample(xout, x, flux)
(Pdb) u
> /project/projectdirs/desi/software/edison/desispec/master/py/desispec/fluxcalibration.py(225)compute_flux_calibration()
-> model_flux[fiber]=resample_flux(stdstars.wave,input_model_wave,input_model_flux[fiber])
(Pdb) print input_model_flux.shape
(1,)
(Pdb) print input_model_flux
[30787]
```

**Comment by moustakas** [comment]
This code relies on a static set of standard-star models, in the example quoted above,
```
/scratch1/scratchdirs/sjbailey/desi/spectro/redux/dailytest/exposures/20151101/00000002/stdstars-sp0-00000002.fits
```
So this isn't building models on-the-fly.

**Comment by gdhungana** [comment]
I was looking into this but discover the following also @sbailey @moustakas . It smells something wrong even if the file is written successfully after 100 iterations (which is probably hard coded limit). In the end it doesn't give chi2, ndf etc as it used to...
$ desi_compute_fiberflat.py --infile 'frame-b0-00000000.fits' --outfile 'fiberflat-b0-00000000.fits' 
INFO:desi_compute_fiberflat.py:31:main: starting
INFO:fiberflat.py:53:compute_fiberflat: starting
INFO:fiberflat.py:127:compute_fiberflat: iter 0 fiber 0
INFO:fiberflat.py:140:compute_fiberflat: iter 0 solving
INFO:fiberflat.py:144:compute_fiberflat: iter 0 smoothing
INFO:fiberflat.py:127:compute_fiberflat: iter 1 fiber 0
INFO:fiberflat.py:140:compute_fiberflat: iter 1 solving
INFO:fiberflat.py:144:compute_fiberflat: iter 1 smoothing
INFO:fiberflat.py:127:compute_fiberflat: iter 2 fiber 0
INFO:fiberflat.py:140:compute_fiberflat: iter 2 solving
INFO:fiberflat.py:144:compute_fiberflat: iter 2 smoothing
INFO:fiberflat.py:127:compute_fiberflat: iter 3 fiber 0
INFO:fiberflat.py:140:compute_fiberflat: iter 3 solving
INFO:fiberflat.py:144:compute_fiberflat: iter 3 smoothing
..........................................................................
........................................................................
INFO:fiberflat.py:144:compute_fiberflat: iter 97 smoothing
INFO:fiberflat.py:127:compute_fiberflat: iter 98 fiber 0
INFO:fiberflat.py:140:compute_fiberflat: iter 98 solving
INFO:fiberflat.py:144:compute_fiberflat: iter 98 smoothing
INFO:fiberflat.py:127:compute_fiberflat: iter 99 fiber 0
INFO:fiberflat.py:140:compute_fiberflat: iter 99 solving
INFO:fiberflat.py:144:compute_fiberflat: iter 99 smoothing
INFO:fiberflat.py:217:compute_fiberflat: nout tot=0
INFO:desi_compute_fiberflat.py:37:main: successfully wrote fiberflat-b0-00000000.fits
