### ISSUE TITLE
intermittent traceshift failure on z2 CCD

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#891]
From the nightwatch/qproc of 20200226/52231:
```
INFO:trace_shifts.py:175:resample_boxcar_frame: resampling with oversampling
INFO:trace_shifts.py:199:resample_boxcar_frame: Resampled 500 fibers in 0.3 sec
INFO:trace_shifts.py:690:shift_ycoef_using_external_spectrum: convolve reference spectrum using PSF at fiber 250 and wavelength 9378A
INFO:trace_shifts.py:698:shift_ycoef_using_external_spectrum: resample convolved reference spectrum
INFO:trace_shifts.py:701:shift_ycoef_using_external_spectrum: absorb difference of calibration
INFO:trace_shifts.py:710:shift_ycoef_using_external_spectrum: fit shifts on wavelength bins
INFO:trace_shifts.py:760:shift_ycoef_using_external_spectrum: polynomial fit of shifts and modification of PSF ycoef
Traceback (most recent call last):
File "/software/datasystems/desiconda/20191002/desispec/master/bin/desi_qproc", line 8, in
qproc.main(qproc.parse())
File "/software/datasystems/desiconda/20191002/desispec/master/py/desispec/scripts/qproc.py", line 218, in main
tset = trace_shifts_script.fit_trace_shifts(image=image,args=tmp_args)
File "/software/datasystems/desiconda/20191002/desispec/master/py/desispec/scripts/trace_shifts.py", line 317, in fit_trace_shifts
degyy=args.degyy,width=7)
File "/software/datasystems/desiconda/20191002/desispec/master/py/desispec/trace_shifts.py", line 762, in shift_ycoef_using_external_spectrum
coef = np.polyfit(wave_for_dy,dy,degyy,w=1./ey**2)
File "<__array_function__ internals>", line 6, in polyfit
File "/software/datasystems/desiconda/20191002/conda/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 601, in polyfit
raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
```

**Comment by sbailey** [comment]
Happened again on 20200306/53601.  Observers report they have seen this before, always on z2.  That CCD has a dead columns artifact that might be confusing trace shifts?

**Comment by julienguy** [comment]
The traces are off by 3 pixels in cross-dispersion. The input fiber traces end up between the actual spectra traces. There is also a bad fiber trace for fiber 225 because of a dead column.

![traces](https://user-images.githubusercontent.com/5192160/76255808-10d8e180-620c-11ea-8956-1fc430644ad2.png)

I have codes to identify and fix this kind of situation. I will push them to a branch of desispec.

**Comment by julienguy** [comment]
I have committed to the branch 'traceshift' the scripts used for the following procedure use to fix the psf of Z2.
I copy the psf file to $DESI_SPECTRO_CALIB in a new version for this camera with a starting date of 20200207 (just after it was cleaned). 

But this tells us we should update all psf files in DESI_SPECTRO_CALIB  asap.

```
# display fiber traces and image
plot_fiber_traces -i $DESI_SPECTRO_CALIB/spec/sm5/psfnight-z2-20200125.fits --image preproc-z2-00053601.fits --vmax 50 --vmin -10

# fix the bad fiber trace by interpolating from neighbors
desi_interpolate_fiber_psf -i $DESI_SPECTRO_CALIB/spec/sm5/psfnight-z2-20200125.fits --fibers 225 -o tmp1.fits

# manually shift in cross dispersion
desi_offset_fiber_traces -i tmp1.fits --dx 3 -o tmp2.fits

# adjust (without the final wavelength adjustment on the sky lines)
desi_compute_trace_shifts -i preproc-z2-00053601.fits --psf tmp2.fits -o tmp3.fits

# verify
plot_fiber_traces -i tmp3.fits  --image preproc-z2-00053601.fits  --vmin -20 --vmax 50

# extract with qproc to see how bad the wavelength solution is,
# use another exposure for that, one with more sky
desi_qproc -i ~/data/20200306/00053741/desi-00053741.fits.fz --cam z2 --psf tmp3.fits -o qframe-z2-00053741.fits
plot_frame -i qframe-z2-00053741.fits --sky --fiber 1100

# clearly off!!
desi_offset_fiber_traces -i tmp3.fits --dy -4 -o tmp4.fits
desi_qproc -i ~/data/20200306/00053741/desi-00053741.fits.fz --cam z2 --psf tmp4.fits -o qframe-z2-00053741.fits
plot_frame -i qframe-z2-00053741.fits --sky --fiber 1100

# now refit, including matching sky 
desi_compute_trace_shifts -i preproc-z2-00053741.fits --auto --psf tmp4.fits -o tmp5.fits

# check it is also working with the dither exposure (which has many more fibers with bright stars)
desi_compute_trace_shifts -i preproc-z2-00053601.fits --auto --psf tmp4.fits -o tmp6.fits

plot_fiber_traces -i tmp6.fits  --image preproc-z2-00053601.fits --vmax 50 --vmin -20
```
![traces2](https://user-images.githubusercontent.com/5192160/76264451-17248900-621f-11ea-8609-cddde2371509.png)

**Comment by julienguy** [comment]
now fixed
