### ISSUE TITLE
Barycentric Corrections fail when both TARGTRA and RA are unassigned

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#896]
Barycentric Correction Fails for some old exposures where the header keys aren't properly labeled. This is a fringe case that hasn't appeared in the most recent month of data.

```
RUNNING: desi_extract_spectra -w 7520.0,9824.0,0.8 -i /global/cfs/cdirs/desi/spectro/redux/daily/preproc/20200122/00043028\
/preproc-z7-00043028.fits -p /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200122/00043028/psf-z7-00043028.fits -\
o /global/cfs/cdirs/desi/spectro/redux/daily/exposures/20200122/00043028/frame-z7-00043028.fits --psferr 0.1 --barycentric\
-correction
Traceback (most recent call last):
  File "/global/homes/k/kremin//workspace/most_recent_calib/desispec/bin/desi_proc", line 664, in <module>
    desispec.scripts.extract.main_mpi(extract_args, comm=comm_extract)
  File "/global/homes/k/kremin/workspace/most_recent_calib/desispec/py/desispec/scripts/extract.py", line 337, in main_mpi
    barycentric_correction_factor = barycentric_correction_multiplicative_factor(img.meta)
  File "/global/homes/k/kremin/workspace/most_recent_calib/desispec/py/desispec/scripts/extract.py", line 95, in barycentr\
ic_correction_multiplicative_factor
    raise KeyError("no TARGTRA nor RA in header")
KeyError: 'no TARGTRA nor RA in header'
```

**Comment by sbailey** [comment]
For this exposure, TARGTRA is in the FIBERMAP HDU but not in the primary HDU.

In the raw data on 20200122, TARGTRA is in the SPS HDU (now called SPEC) but not in the per-camera HDUs.  More recent data has it in the per-camera HDUs too.

desispec could try using the fibermap header (fibermap.met) if the img.meta header fails.
