### ISSUE TITLE
sky model failure 

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#906]
```
desi_proc --mpi --traceshift --scattered-light --nofluxcalib \
  --cameras z4 -n 20200306 -e 53630
```
fails with
```
INFO:sky.py:239:compute_uniform_sky: iter 8 compute chi2
INFO:sky.py:247:compute_uniform_sky: rejecting
INFO:sky.py:278:compute_uniform_sky: iter #8 chi2=nan ndf=317806 chi2pdf=nan nout=0
INFO:sky.py:283:compute_uniform_sky: nout tot=2957
INFO:sky.py:292:compute_uniform_sky: compute the parameter covariance
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:254: RuntimeWarning: invalid value encountered in greater
  nout_per_wave=np.sum(chi2>nsig_clipping**2,axis=0)
...
  bad=(chi2>nsig_clipping**2)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:274: RuntimeWarning: invalid value encountered in greater
  ndf=int(np.sum(chi2>0)-nwave)
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/bin/desi_compute_sky", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.33.0', 'desi_compute_sky')
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/EGG-INFO/scripts/desi_compute_sky", line 16, in <module>
    sky.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/scripts/sky.py", line 68, in main
    skymodel = compute_sky(frame,add_variance=(not args.no_extra_variance),angular_variation_deg=args.angular_variation_deg,chromatic_variation_deg=args.chromatic_variation_deg)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py", line 45, in compute_sky
    skymodel = compute_uniform_sky(frame, nsig_clipping=nsig_clipping,max_iterations=max_iterations,model_ivar=model_ivar,add_variance=add_variance)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py", line 297, in compute_uniform_sky
    parameter_covar=cholesky_invert(A)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/linalg.py", line 64, in cholesky_invert
    UorL,lower = scipy.linalg.cho_factor(A,overwrite_a=False)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 155, in cho_factor
    check_finite=check_finite)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 19, in _cholesky
    a1 = asarray_chkfinite(a) if check_finite else asarray(a)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by sbailey** [comment]
Tested and this one still crashes with latest calibs.

**Comment by sbailey** [comment]
z4 amp C was terrible on that exposure (and multiple other exposures that night):
![image](https://user-images.githubusercontent.com/218471/77812155-b4bfeb00-705c-11ea-9c48-6ea344104d8c.png)
This resulted in large patches of masked pixels which resulted in singular matrices while extracting the spectra which resulted in flux=NaN which eventually crashed sky subtraction.  So:
  * the hardware had a problem, which it shouldn't have, but sometimes that happens
  * even if the hardware has a problem, specter shouldn't return NaN flux
  * sky subtraction crashing when given NaN input is actually a semi-reasonable thing to do

I'll make an update in Specter to catch singular matrices and return mask!=0 flux=ivar=0 instead of NaN.
