### ISSUE TITLE
negative ivar failure

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#907]
```
desi_proc --mpi --traceshift --scattered-light --nofluxcalib  \
   --cameras r0,z4 -n 20200306 -e 53638
```
crashes with
```
WARNING:sky.py:1154:subtract_sky: throughput corr error = 0.0670 is too large compared to the correction value = -0.0014 for fiber #498, do not apply correction
WARNING:sky.py:1100:subtract_sky: cannot corr. throughput. for fiber 499
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:1105: RuntimeWarning: invalid value encountered in greater
  ivar=(var>0)/(var+(var==0)+0.005**2)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:1106: RuntimeWarning: invalid value encountered in greater
  ivar_for_outliers=(var>0)/(var+(var==0)+0.02**2)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:1123: RuntimeWarning: invalid value encountered in greater
  if chi2[worst]>nsig**2*np.median(chi2[chi2>0]) : # with rough scaling of errors
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3118: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/util.py:311: RuntimeWarning: invalid value encountered in greater_equal
  assert np.all(iv1 >= 0), 'ivar1 has negative elements'
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/bin/desi_proc", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.33.0', 'desi_proc')
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/EGG-INFO/scripts/desi_proc", line 912, in <module>
    subtract_sky(frame, sky, throughput_correction=True)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py", line 1163, in subtract_sky
    frame.ivar = util.combine_ivar(frame.ivar, skymodel.ivar)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/util.py", line 311, in combine_ivar
    assert np.all(iv1 >= 0), 'ivar1 has negative elements'
AssertionError: ivar1 has negative elements
```

and 

```
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:265: RuntimeWarning: invalid value encountered in greater
  bad=(chi2>nsig_clipping**2)
/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py:274: RuntimeWarning: invalid value encountered in greater
  ndf=int(np.sum(chi2>0)-nwave)
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/bin/desi_compute_sky", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.33.0', 'desi_compute_sky')
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/EGG-INFO/scripts/desi_compute_sky", line 16, in <module>
    sky.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/scripts/sky.py", line 68, in main
    skymodel = compute_sky(frame,add_variance=(not args.no_extra_variance),angular_variation_deg=args.angular_variation_deg,chromatic_variation_deg=args.chromatic_variation_deg)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py", line 45, in compute_sky
    skymodel = compute_uniform_sky(frame, nsig_clipping=nsig_clipping,max_iterations=max_iterations,model_ivar=model_ivar,add_variance=add_variance)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/sky.py", line 297, in compute_uniform_sky
    parameter_covar=cholesky_invert(A)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.33.0/lib/python3.6/site-packages/desispec-0.33.0-py3.6.egg/desispec/linalg.py", line 64, in cholesky_invert
    UorL,lower = scipy.linalg.cho_factor(A,overwrite_a=False)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 155, in cho_factor
    check_finite=check_finite)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/scipy/linalg/decomp_cholesky.py", line 19, in _cholesky
    a1 = asarray_chkfinite(a) if check_finite else asarray(a)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

**Comment by sbailey** [comment]
No longer crashes with latest calibs.  Closing.
