### ISSUE TITLE
Add ability to coadd coadds

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#919]
e.g. starting from a coadd across exposures but not across cameras, it would be nice to be able to then coadd across cameras.  But:
```
%> desi_coadd_spectra -i $SCRATCH/coadd-0.fits -o $SCRATCH/coaddcams-0.fits --coadd-cameras
INFO:coadd_spectra.py:54:main: reading spectra ...
INFO:coadd_spectra.py:74:main: coadding cameras ...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/bin/desi_coadd_spectra", line 16, in <module>
    coadd_spectra.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/scripts/coadd_spectra.py", line 75, in main
    spectra = coadd_cameras(spectra,cosmics_nsig=args.nsig)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/coaddition.py", line 342, in coadd_cameras
    fibermap=coadd_fibermap(spectra.fibermap)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/coaddition.py", line 53, in coadd_fibermap
    tfmap.add_column(xx,name='FIRST_'+k)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 1569, in add_column
    self.add_columns([col], [index], name, rename_duplicate=rename_duplicate)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 1708, in add_columns
    self._init_from_cols(newcols)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 758, in _init_from_cols
    self._make_table_from_cols(self, newcols)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/table/table.py", line 803, in _make_table_from_cols
    raise ValueError('Duplicate column names')
ValueError: Duplicate column names
```

This is because coadds add some columns like FIRST_EXPID, FIRST_NIGHT, etc. and then the second coadd tries to add them again and fails.

**Comment by akremin** [comment]
Solved for adding across cameras in PR #948
