### ISSUE TITLE
desi_coadd_spectra appears to fail when all spectrographs don't have the same number of cframes

### ISSUE THREAD

**Issue by akremin** [desihub/desispec#923]
```
export SPECTRO=1
export TILEID=65008
export NIGHT=20200314
cd ${DESI_SPECTRO_REDUX}/${SPECPROD}/tiles/${TILEID}/${NIGHT}
srun -N 1 -n 1 -c 64 desi_coadd_spectra --coadd-cameras --nproc 16 -i cframe-?${SPECTRO}-*.fits -o coadd-${SPECTRO}-${TILEID}-${NIGHT}.fits
```

Output:

```
INFO:coadd_spectra.py:54:main: reading spectra ...
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/bin/desi_coadd_spectra", line 16, in <module>
    coadd_spectra.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/scripts/coadd_spectra.py", line 66, in main
    spectra = frames2spectra(frames)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/pixgroup.py", line 531, in frames2spectra
    return SpectraLite(bands, wave, flux, ivar, mask, resolution_data, fibermap, scores)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/master/py/desispec/pixgroup.py", line 227, in __init__
    assert flux[x].shape[0] == nspec
AssertionError
srun: error: nid00058: task 0: Exited with exit code 1
```

This fails for 5 spectrographs (1, 4, 7, 8, 9) while succeeding for 5 spectrographs (0, 2, 3, 5, 6). The successful ones have 2 cframes for each of b, r, z while the failed ones have 3 cframes. My hypothesis is that the 0th defined the number of expected frames to be 2, which is true for the other successful spectrographs SP2, 3, 5, and 6, but not true for the failed ones.

See the file lists in the example directory:

![image](https://user-images.githubusercontent.com/8572603/77007793-1330ef00-6922-11ea-8f26-a0af8257e652.png)

**Comment by sbailey** [comment]
Fixed by PR #927
