### ISSUE TITLE
z2 traceshifts failing

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#952]
When running with desispec/0.34.0 and desi_spectro_calib/0.1:
```
desi_compute_trace_shifts -i /global/cfs/cdirs/desi/spectro/redux/andes/preproc/20200219/00051002/preproc-z2-00051002.fits \
    --psf /global/cfs/cdirs/desi/spectro/desi_spectro_calib/0.1/spec/sm5/psfnight-z2-20200125-shifted-20200306.fits \
    --degxx 2 --degxy 0 --degyx 2 --degyy 0 --sky \
    --outpsf $SCRATCH/temp/psf-z2-00051002.fits
```
```
...
INFO:trace_shifts.py:760:shift_ycoef_using_external_spectrum: polynomial fit of shifts and modification of PSF ycoef
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.0/bin/desi_compute_trace_shifts", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.34.0', 'desi_compute_trace_shifts')
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.0/lib/python3.6/site-packages/desispec-0.34.0-py3.6.egg/EGG-INFO/scripts/desi_compute_trace_shifts", line 16, in <module>
    trace_shifts.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.0/lib/python3.6/site-packages/desispec-0.34.0-py3.6.egg/desispec/scripts/trace_shifts.py", line 348, in main
    tset = fit_trace_shifts(image=image,args=args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.0/lib/python3.6/site-packages/desispec-0.34.0-py3.6.egg/desispec/scripts/trace_shifts.py", line 317, in fit_trace_shifts
    degyy=args.degyy,width=7)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.0/lib/python3.6/site-packages/desispec-0.34.0-py3.6.egg/desispec/trace_shifts.py", line 762, in shift_ycoef_using_external_spectrum
    coef = np.polyfit(wave_for_dy,dy,degyy,w=1./ey**2)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/polynomial.py", line 598, in polyfit
    raise TypeError("expected non-empty vector for x")
TypeError: expected non-empty vector for x
```

**Comment by julienguy** [comment]
It's not what I would call a bug. The wavelength calibration of the PSF used for trace shifts is off by 3.3A. I fixed this by having a larger scan range for the wavelength offset from +-3A to +-10A.

I pushed the 1line  change to master.
