### ISSUE TITLE
desi_compute_trace_shifts crash 20200307/54151 z6

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#962]
Using desispec/0.34.4:
```
desi_compute_trace_shifts -i /global/cfs/cdirs/desi/spectro/redux/andes/preproc/20200307/00054151/preproc-z6-00054151.fits \
    --psf /global/cfs/cdirs/desi/spectro/desi_spectro_calib/0.1.1/spec/sm7/psfnight-z6-20200306-20200315.fits \
    --outpsf $SCRATCH/shifted-input-psf-z6-00054151.fits --degxx 0 --degxy 0 --degyx 0 --degyy 0 --arc-lamps
...
WARNING:qextract.py:149:qproc_boxcar_extraction: setting up a fibermap to save the FIBER identifiers
INFO:trace_shifts.py:175:resample_boxcar_frame: resampling with oversampling
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.4/bin/desi_compute_trace_shifts", line 4, in <module>
    __import__('pkg_resources').run_script('desispec==0.34.4', 'desi_compute_trace_shifts')
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.4/lib/python3.6/site-packages/desispec-0.34.4-py3.6.egg/EGG-INFO/scripts/desi_compute_trace_shifts", line 16, in <module>
    trace_shifts.main(args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.4/lib/python3.6/site-packages/desispec-0.34.4-py3.6.egg/desispec/scripts/trace_shifts.py", line 353, in main
    tset = fit_trace_shifts(image=image,args=args)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.4/lib/python3.6/site-packages/desispec-0.34.4-py3.6.egg/desispec/scripts/trace_shifts.py", line 200, in fit_trace_shifts
    x_for_dy,y_for_dy,dy,ey,fiber_for_dy,wave_for_dy = compute_dy_using_boxcar_extraction(tset, image=image, fibers=fibers, width=args.width)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.4/lib/python3.6/site-packages/desispec-0.34.4-py3.6.egg/desispec/trace_shifts.py", line 413, in compute_dy_using_boxcar_extraction
    flux, ivar, wave = resample_boxcar_frame(qframe.flux, qframe.ivar, qframe.wave, oversampling=4)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/desispec/0.34.4/lib/python3.6/site-packages/desispec-0.34.4-py3.6.egg/desispec/trace_shifts.py", line 195, in resample_boxcar_frame
    flux[i] = np.interp(wave, frame_wave[i][j],frame_flux[i][j],left=0,right=0)
  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/numpy/lib/function_base.py", line 1412, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty
```

The z6 data for that exposure are terrible, but we still shouldn't crash.
![image](https://user-images.githubusercontent.com/218471/80161704-10ab6000-8586-11ea-9766-62047028f520.png)

**Comment by sbailey** [comment]
0307 was so messed up that we dropped it from processing.  Firmware was fixed.  Closing this ticket as "wontfix" (for now...) even though we didn't update it to "data for that exposure are terrible, but we still shouldn't crash".  We can revive this is crashes on terrible data become problematic.
